/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * ATSPM Report Api
 * ATSPM Reporting with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  ApproachDelayOptions,
  ApproachDelayResult,
  ProblemDetails
} from '../report-api.schemas';

import { reportsRequest } from '../../../lib/axios';




export type getApproachDelayTestDataResponse200 = {
  data: ApproachDelayResult[]
  status: 200
}

export type getApproachDelayTestDataResponse406 = {
  data: ProblemDetails
  status: 406
}

export type getApproachDelayTestDataResponseSuccess = (getApproachDelayTestDataResponse200) & {
  headers: Headers;
};
export type getApproachDelayTestDataResponseError = (getApproachDelayTestDataResponse406) & {
  headers: Headers;
};

export type getApproachDelayTestDataResponse = (getApproachDelayTestDataResponseSuccess | getApproachDelayTestDataResponseError)

export const getGetApproachDelayTestDataUrl = () => {




  return `/api/v1/ApproachDelay/test`
}

/**
 * @summary Get example data for testing
 */
export const getApproachDelayTestData = async ( options?: RequestInit): Promise<getApproachDelayTestDataResponse> => {

  return reportsRequest<getApproachDelayTestDataResponse>(getGetApproachDelayTestDataUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApproachDelayTestDataQueryKey = () => {
    return [
    `/api/v1/ApproachDelay/test`
    ] as const;
    }


export const getGetApproachDelayTestDataQueryOptions = <TData = Awaited<ReturnType<typeof getApproachDelayTestData>>, TError = ProblemDetails>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApproachDelayTestData>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApproachDelayTestDataQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApproachDelayTestData>>> = ({ signal }) => getApproachDelayTestData({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApproachDelayTestData>>, TError, TData> & { queryKey: QueryKey }
}

export type GetApproachDelayTestDataQueryResult = NonNullable<Awaited<ReturnType<typeof getApproachDelayTestData>>>
export type GetApproachDelayTestDataQueryError = ProblemDetails


/**
 * @summary Get example data for testing
 */

export function useGetApproachDelayTestData<TData = Awaited<ReturnType<typeof getApproachDelayTestData>>, TError = ProblemDetails>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getApproachDelayTestData>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetApproachDelayTestDataQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getApproachDelayReportDataResponse200 = {
  data: ApproachDelayResult[]
  status: 200
}

export type getApproachDelayReportDataResponse400 = {
  data: ProblemDetails
  status: 400
}

export type getApproachDelayReportDataResponse406 = {
  data: ProblemDetails
  status: 406
}

export type getApproachDelayReportDataResponseSuccess = (getApproachDelayReportDataResponse200) & {
  headers: Headers;
};
export type getApproachDelayReportDataResponseError = (getApproachDelayReportDataResponse400 | getApproachDelayReportDataResponse406) & {
  headers: Headers;
};

export type getApproachDelayReportDataResponse = (getApproachDelayReportDataResponseSuccess | getApproachDelayReportDataResponseError)

export const getGetApproachDelayReportDataUrl = () => {




  return `/api/v1/ApproachDelay/getReportData`
}

/**
 * @summary Get report data
 */
export const getApproachDelayReportData = async (approachDelayOptions?: ApproachDelayOptions, options?: RequestInit): Promise<getApproachDelayReportDataResponse> => {

  return reportsRequest<getApproachDelayReportDataResponse>(getGetApproachDelayReportDataUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      approachDelayOptions,)
  }
);}




export const getGetApproachDelayReportDataMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApproachDelayReportData>>, TError,{data?: ApproachDelayOptions}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getApproachDelayReportData>>, TError,{data?: ApproachDelayOptions}, TContext> => {

const mutationKey = ['getApproachDelayReportData'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getApproachDelayReportData>>, {data?: ApproachDelayOptions}> = (props) => {
          const {data} = props ?? {};

          return  getApproachDelayReportData(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetApproachDelayReportDataMutationResult = NonNullable<Awaited<ReturnType<typeof getApproachDelayReportData>>>
    export type GetApproachDelayReportDataMutationBody = ApproachDelayOptions | undefined
    export type GetApproachDelayReportDataMutationError = ProblemDetails

    /**
 * @summary Get report data
 */
export const useGetApproachDelayReportData = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getApproachDelayReportData>>, TError,{data?: ApproachDelayOptions}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof getApproachDelayReportData>>,
        TError,
        {data?: ApproachDelayOptions},
        TContext
      > => {
      return useMutation(getGetApproachDelayReportDataMutationOptions(options));
    }
