/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ATSPM Report Api
 * ATSPM Reporting with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  PedActuationResult
} from '../report-api.schemas';

import {
  getGetLeftTurnPedActuationReportDataResponseMock,
  getGetLeftTurnPedActuationTestDataResponseMock
} from './left-turn-ped-actuation.faker';

export { getGetLeftTurnPedActuationTestDataResponseMock, getGetLeftTurnPedActuationReportDataResponseMock } from './left-turn-ped-actuation.faker';


export const getGetLeftTurnPedActuationTestDataMockHandler = (overrideResponse?: PedActuationResult | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PedActuationResult> | PedActuationResult), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/LeftTurnPedActuation/test', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetLeftTurnPedActuationTestDataResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetLeftTurnPedActuationReportDataMockHandler = (overrideResponse?: PedActuationResult | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PedActuationResult> | PedActuationResult), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/LeftTurnPedActuation/getReportData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetLeftTurnPedActuationReportDataResponseMock(),
      { status: 200
      })
  }, options)
}
export const getLeftTurnPedActuationMock = () => [
  getGetLeftTurnPedActuationTestDataMockHandler(),
  getGetLeftTurnPedActuationReportDataMockHandler()
]
