/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * ATSPM Report Api
 * ATSPM Reporting with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  PedActuationOptions,
  PedActuationResult,
  ProblemDetails
} from '../report-api.schemas';

import { reportsRequest } from '../../../lib/axios';




export type getLeftTurnPedActuationTestDataResponse200 = {
  data: PedActuationResult
  status: 200
}

export type getLeftTurnPedActuationTestDataResponse406 = {
  data: ProblemDetails
  status: 406
}

export type getLeftTurnPedActuationTestDataResponseSuccess = (getLeftTurnPedActuationTestDataResponse200) & {
  headers: Headers;
};
export type getLeftTurnPedActuationTestDataResponseError = (getLeftTurnPedActuationTestDataResponse406) & {
  headers: Headers;
};

export type getLeftTurnPedActuationTestDataResponse = (getLeftTurnPedActuationTestDataResponseSuccess | getLeftTurnPedActuationTestDataResponseError)

export const getGetLeftTurnPedActuationTestDataUrl = () => {




  return `/api/v1/LeftTurnPedActuation/test`
}

/**
 * @summary Get example data for testing
 */
export const getLeftTurnPedActuationTestData = async ( options?: RequestInit): Promise<getLeftTurnPedActuationTestDataResponse> => {

  return reportsRequest<getLeftTurnPedActuationTestDataResponse>(getGetLeftTurnPedActuationTestDataUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLeftTurnPedActuationTestDataQueryKey = () => {
    return [
    `/api/v1/LeftTurnPedActuation/test`
    ] as const;
    }


export const getGetLeftTurnPedActuationTestDataQueryOptions = <TData = Awaited<ReturnType<typeof getLeftTurnPedActuationTestData>>, TError = ProblemDetails>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLeftTurnPedActuationTestData>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLeftTurnPedActuationTestDataQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLeftTurnPedActuationTestData>>> = ({ signal }) => getLeftTurnPedActuationTestData({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLeftTurnPedActuationTestData>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLeftTurnPedActuationTestDataQueryResult = NonNullable<Awaited<ReturnType<typeof getLeftTurnPedActuationTestData>>>
export type GetLeftTurnPedActuationTestDataQueryError = ProblemDetails


/**
 * @summary Get example data for testing
 */

export function useGetLeftTurnPedActuationTestData<TData = Awaited<ReturnType<typeof getLeftTurnPedActuationTestData>>, TError = ProblemDetails>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLeftTurnPedActuationTestData>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetLeftTurnPedActuationTestDataQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getLeftTurnPedActuationReportDataResponse200 = {
  data: PedActuationResult
  status: 200
}

export type getLeftTurnPedActuationReportDataResponse400 = {
  data: ProblemDetails
  status: 400
}

export type getLeftTurnPedActuationReportDataResponse406 = {
  data: ProblemDetails
  status: 406
}

export type getLeftTurnPedActuationReportDataResponseSuccess = (getLeftTurnPedActuationReportDataResponse200) & {
  headers: Headers;
};
export type getLeftTurnPedActuationReportDataResponseError = (getLeftTurnPedActuationReportDataResponse400 | getLeftTurnPedActuationReportDataResponse406) & {
  headers: Headers;
};

export type getLeftTurnPedActuationReportDataResponse = (getLeftTurnPedActuationReportDataResponseSuccess | getLeftTurnPedActuationReportDataResponseError)

export const getGetLeftTurnPedActuationReportDataUrl = () => {




  return `/api/v1/LeftTurnPedActuation/getReportData`
}

/**
 * @summary Get report data
 */
export const getLeftTurnPedActuationReportData = async (pedActuationOptions?: PedActuationOptions, options?: RequestInit): Promise<getLeftTurnPedActuationReportDataResponse> => {

  return reportsRequest<getLeftTurnPedActuationReportDataResponse>(getGetLeftTurnPedActuationReportDataUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pedActuationOptions,)
  }
);}




export const getGetLeftTurnPedActuationReportDataMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLeftTurnPedActuationReportData>>, TError,{data?: PedActuationOptions}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getLeftTurnPedActuationReportData>>, TError,{data?: PedActuationOptions}, TContext> => {

const mutationKey = ['getLeftTurnPedActuationReportData'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getLeftTurnPedActuationReportData>>, {data?: PedActuationOptions}> = (props) => {
          const {data} = props ?? {};

          return  getLeftTurnPedActuationReportData(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetLeftTurnPedActuationReportDataMutationResult = NonNullable<Awaited<ReturnType<typeof getLeftTurnPedActuationReportData>>>
    export type GetLeftTurnPedActuationReportDataMutationBody = PedActuationOptions | undefined
    export type GetLeftTurnPedActuationReportDataMutationError = ProblemDetails

    /**
 * @summary Get report data
 */
export const useGetLeftTurnPedActuationReportData = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLeftTurnPedActuationReportData>>, TError,{data?: PedActuationOptions}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof getLeftTurnPedActuationReportData>>,
        TError,
        {data?: PedActuationOptions},
        TContext
      > => {
      return useMutation(getGetLeftTurnPedActuationReportDataMutationOptions(options));
    }
