/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ATSPM Report Api
 * ATSPM Reporting with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  TimeSpaceDiagramPhaseResult,
  TimeSpaceDiagramSrmPhaseOverlay
} from '../report-api.schemas';

import {
  getGetTimeSpaceDiagramReportDataResponseMock,
  getGetTimeSpaceDiagramSrmDataResponseMock,
  getGetTimeSpaceDiagramTestDataResponseMock
} from './time-space-diagram.faker';

export { getGetTimeSpaceDiagramSrmDataResponseMock, getGetTimeSpaceDiagramTestDataResponseMock, getGetTimeSpaceDiagramReportDataResponseMock } from './time-space-diagram.faker';


export const getGetTimeSpaceDiagramSrmDataMockHandler = (overrideResponse?: TimeSpaceDiagramSrmPhaseOverlay[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TimeSpaceDiagramSrmPhaseOverlay[]> | TimeSpaceDiagramSrmPhaseOverlay[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/TimeSpaceDiagram/getSrmData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetTimeSpaceDiagramSrmDataResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetTimeSpaceDiagramTestDataMockHandler = (overrideResponse?: TimeSpaceDiagramPhaseResult[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TimeSpaceDiagramPhaseResult[]> | TimeSpaceDiagramPhaseResult[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/TimeSpaceDiagram/test', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetTimeSpaceDiagramTestDataResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetTimeSpaceDiagramReportDataMockHandler = (overrideResponse?: TimeSpaceDiagramPhaseResult[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TimeSpaceDiagramPhaseResult[]> | TimeSpaceDiagramPhaseResult[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/TimeSpaceDiagram/getReportData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetTimeSpaceDiagramReportDataResponseMock(),
      { status: 200
      })
  }, options)
}
export const getTimeSpaceDiagramMock = () => [
  getGetTimeSpaceDiagramSrmDataMockHandler(),
  getGetTimeSpaceDiagramTestDataMockHandler(),
  getGetTimeSpaceDiagramReportDataMockHandler()
]
