#region license
// Copyright 2026 Utah Departement of Transportation
// for Infrastructure - Utah.Udot.Atspm.Infrastructure.Extensions/MoveToToolkit.cs
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#endregion

using System.ComponentModel;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks.Dataflow;
using Utah.Udot.NetStandardToolkit.Workflows;

namespace Utah.Udot.Atspm.Infrastructure.Extensions
{
    /// <summary>
    /// Provides utility methods for generating and hashing secure API keys.
    /// </summary>
    public static class ApiKeyGenerator
    {
        /// <summary>
        /// Computes a SHA256 hash of the provided raw API key.
        /// </summary>
        /// <param name="rawKey">The plain-text API key to hash.</param>
        /// <returns>A Base64-encoded string representing the hashed key.</returns>
        /// <remarks>
        /// This should be used to store keys in the database so that plain-text 
        /// keys are never exposed if the data is compromised.
        /// </remarks>
        public static string HashKey(string rawKey)
        {
            var inputBytes = Encoding.UTF8.GetBytes(rawKey);
            var hashBytes = SHA256.HashData(inputBytes);
            return Convert.ToBase64String(hashBytes);
        }

        /// <summary>
        /// Creates a new cryptographically secure API key and its corresponding hash.
        /// </summary>
        /// <returns>
        /// A tuple containing:
        /// <list type="bullet">
        /// <item><description><c>RawKey</c>: The plain-text key to be shown to the user once.</description></item>
        /// <item><description><c>Hash</c>: The hashed version of the key to be stored in the database.</description></item>
        /// </list>
        /// </returns>
        /// <remarks>
        /// The raw key is sanitized to remove non-alphanumeric Base64 characters (+, /, =) 
        /// for better compatibility in headers and URLs.
        /// </remarks>
        public static (string RawKey, string Hash) CreateKey()
        {
            var bytes = RandomNumberGenerator.GetBytes(32);
            string rawKey = Convert.ToBase64String(bytes)
                .Replace("/", "").Replace("+", "").Replace("=", "");

            return (rawKey, HashKey(rawKey));
        }
    }

    public static class TempHelpers
    {
        /// <summary>
        /// Provides a <see cref="Task"/> that completes when the <see cref="ISupportInitializeNotification"/> 
        /// service has finished initialization.
        /// </summary>
        /// <param name="service">The service to monitor for initialization.</param>
        /// <returns>
        /// A <see cref="Task"/> that represents the initialization process. 
        /// If the service is already initialized, the returned task will be already completed.
        /// </returns>
        /// <remarks>
        /// This method uses <see cref="TaskCompletionSource{TResult}"/> to wrap the 
        /// <see cref="ISupportInitializeNotification.Initialized"/> event. 
        /// It ensures that the event handler is properly unsubscribed once the initialization 
        /// is detected to prevent memory leaks.
        /// </remarks>
        public static Task WhenInitialized(this ISupportInitializeNotification service)
        {
            var tcs = new TaskCompletionSource<bool>();

            if (service.IsInitialized) return Task.CompletedTask;

            EventHandler handler = null;
            handler = (s, e) =>
            {
                service.Initialized -= handler;
                tcs.TrySetResult(true);
            };

            service.Initialized += handler;

            if (service.IsInitialized)
            {
                service.Initialized -= handler;
                tcs.TrySetResult(true);
            }

            return tcs.Task;
        }

        /// <summary>
        /// Executes multiple isolated instances of a workflow in parallel by chunking the input source into batches.
        /// </summary>
        /// <typeparam name="TInput">The type of the input data items to be processed.</typeparam>
        /// <typeparam name="TOutput">The type of the output data generated by the workflow.</typeparam>
        /// <param name="factory">A delegate factory used to instantiate a fresh, isolated workflow for each parallel batch.</param>
        /// <param name="source">An asynchronous stream of input data items.</param>
        /// <param name="batchSize">The number of items to include in each chunk/batch.</param>
        /// <param name="parallelInstances">The maximum number of workflow instances to run concurrently.</param>
        /// <param name="cancellationToken">A token to monitor for cancellation requests.</param>
        /// <returns>A task that represents the completion of all batches across all workflow instances.</returns>
        /// <remarks>
        /// This method uses a <see cref="BatchBlock{T}"/> to group items and an <see cref="ActionBlock{TInput}"/> 
        /// to manage the parallel workflow lifecycle. It includes a polling mechanism to ensure the workflow 
        /// base class has completed its background initialization before data is sent to the input block.
        /// </remarks>
        public static async Task BatchRunAsync<TInput, TOutput>(
            this Func<WorkflowBase<TInput, TOutput>> factory,
            IAsyncEnumerable<TInput> source,
            int batchSize,
            int parallelInstances,
            CancellationToken cancellationToken)
        {
            var batcher = new BatchBlock<TInput>(batchSize, new GroupingDataflowBlockOptions
            {
                BoundedCapacity = batchSize * (parallelInstances + 2),
                CancellationToken = cancellationToken
            });

            var manager = new ActionBlock<TInput[]>(async chunk =>
            {
                using var workflow = factory();

                #region Remove when base services are fixed

                int attempts = 0;
                while (workflow.Input == null && attempts < 150)
                {
                    await Task.Delay(50, cancellationToken);
                    attempts++;
                }

                attempts = 0;
                while (!workflow.IsInitialized && attempts < 150)
                {
                    await Task.Delay(50, cancellationToken);
                    attempts++;
                }

                #endregion

                foreach (var item in chunk)
                {
                    await workflow.Input.SendAsync(item, cancellationToken);
                }

                workflow.Input.Complete();
                await Task.WhenAll(workflow.Steps.Select(s => s.Completion));
            },
            new ExecutionDataflowBlockOptions
            {
                MaxDegreeOfParallelism = parallelInstances,
                BoundedCapacity = parallelInstances + 1,
                CancellationToken = cancellationToken
            });

            batcher.LinkTo(manager, new DataflowLinkOptions { PropagateCompletion = true });

            await foreach (var item in source.WithCancellation(cancellationToken))
            {
                await batcher.SendAsync(item, cancellationToken);
            }

            batcher.Complete();
            await manager.Completion;
        }
    }
}
}
