/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * ATSPM Configuration Api
 * ATSPM Configuration with OData, OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
export type ApiVVersionApiVersionWatchDogIgnoreEventKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionWatchDogIgnoreEventKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionWatchDogIgnoreEventKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionWatchDogIgnoreEventCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionWatchDogIgnoreEventParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionWatchDogIgnoreEventParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionVersionHistoryKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionVersionHistoryKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionVersionHistoryKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionVersionHistoryCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionVersionHistoryParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionVersionHistoryParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionRouteLocationKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRouteLocationKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRouteLocationKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRouteLocationCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionRouteLocationParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRouteLocationParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionRouteDistanceKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRouteDistanceKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRouteDistanceKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRouteDistanceCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionRouteDistanceParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRouteDistanceParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionRouteDistanceGetRouteDistanceByLocationIdentifiersLocationALocationALocationBLocationBParams = {
select?: string;
};

export type ApiVVersionApiVersionRouteDistanceKeyNextLocationsCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionRouteDistanceKeyNextLocationsParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionRouteDistanceKeyPreviousLocationsCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionRouteDistanceKeyPreviousLocationsParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionRouteKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRouteKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRouteKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRouteCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionRouteParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRouteParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type GetApiV1GetRouteViewIdParams = {
includeLocationDetail?: boolean;
'api-version': string;
select?: string;
expand?: string;
};

export type PostApiV1UpsertRouteParams = {
'api-version': string;
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRouteKeyRouteLocationsCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionRouteKeyRouteLocationsParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionRegionCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionRegionKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRegionKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRegionKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRegionParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionRegionParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionRegionKeyLocationsCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionRegionKeyLocationsParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionProductKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionProductKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionProductKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionProductCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionProductParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionProductParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMenuItemsKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMenuItemsKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMenuItemsKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMenuItemsCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMenuItemsParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMenuItemsParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMeasureTypeKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMeasureTypeKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMeasureTypeKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMeasureTypeCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMeasureTypeParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMeasureTypeParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMeasureTypeKeyMeasureCommentsCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMeasureTypeKeyMeasureCommentsParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMeasureTypeKeyDetectionTypesCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMeasureTypeKeyDetectionTypesParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMeasureOptionKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMeasureOptionKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMeasureOptionKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMeasureOptionCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMeasureOptionParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMeasureOptionParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMeasureCommentKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMeasureCommentKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMeasureCommentKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMeasureCommentCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMeasureCommentParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMeasureCommentParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMeasureCommentKeyMeasureTypesCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMeasureCommentKeyMeasureTypesParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMapLayerKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMapLayerKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMapLayerKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMapLayerCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionMapLayerParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionMapLayerParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationTypeKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionLocationTypeKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionLocationTypeKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionLocationTypeCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationTypeParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionLocationTypeParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationTypeKeyLocationsCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationTypeKeyLocationsParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionLocationKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionLocationKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionLocationCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionLocationParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationGetLocationsForSearchParams = {
/**
 * Locations by area
 */
areaId?: number;
/**
 * Locations by region
 */
regionId?: number;
/**
 * Locations by jurisdiction
 */
jurisdictionId?: number;
/**
 * Locations by chart type
 */
metricTypeId?: number;
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationGetDetectionTypeCountParams = {
date?: string;
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationGetLatestVersionOfAllLocationsParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationGetAllVersionsOfLocationIdentifierIdentifierParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationGetLatestVersionOfLocationIdentifierIdentifierParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionLocationKeySetLocationToDeletedParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionLocationKeySaveTemplatedLocationParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionLocationKeySyncLocationParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionLocationKeyCopyLocationToNewVersionParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionLocationKeyDevicesCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationKeyDevicesParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationKeyAreasCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationKeyAreasParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationKeyApproachesCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionLocationKeyApproachesParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionJurisdictionCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionJurisdictionKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionJurisdictionKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionJurisdictionKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionJurisdictionParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionJurisdictionParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionJurisdictionKeyLocationsCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionJurisdictionKeyLocationsParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionFaqCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionFaqKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionFaqKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionFaqKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionFaqParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionFaqParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDirectionTypeKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDirectionTypeKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDirectionTypeKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDirectionTypeCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDirectionTypeParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDirectionTypeParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDirectionTypeKeyOpposingDirectionsCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDirectionTypeKeyOpposingDirectionsParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDirectionTypeKeyPrimaryDirectionsCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDirectionTypeKeyPrimaryDirectionsParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDirectionTypeKeyApproachesCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDirectionTypeKeyApproachesParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDeviceConfigurationKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDeviceConfigurationKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDeviceConfigurationKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDeviceConfigurationCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDeviceConfigurationParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDeviceConfigurationParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDeviceConfigurationKeyDevicesCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDeviceConfigurationKeyDevicesParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDeviceKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDeviceKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDeviceKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDeviceCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDeviceParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDeviceParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDeviceGetActiveDevicesCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDeviceGetActiveDevicesByLocationLocationIdLocationIdParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDetectorCommentKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDetectorCommentKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDetectorCommentKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDetectorCommentCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDetectorCommentParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDetectorCommentParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDetectorKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDetectorKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDetectorKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDetectorCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDetectorParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDetectorParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDetectorKeyDetectionTypesCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDetectorKeyDetectionTypesParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDetectorKeyDetectorCommentsCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDetectorKeyDetectorCommentsParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDetectionTypeKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDetectionTypeKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDetectionTypeKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDetectionTypeCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDetectionTypeParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionDetectionTypeParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDetectionTypeKeyMeasureTypesCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDetectionTypeKeyMeasureTypesParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDetectionTypeKeyDetectorsCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionDetectionTypeKeyDetectorsParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionAreaCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionAreaKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionAreaKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionAreaKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionAreaParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionAreaParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionAreaKeyLocationsCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionAreaKeyLocationsParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionApproachCountParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionApproachKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionApproachKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionApproachKeyParams = {
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionApproachParams = {
select?: string;
expand?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionApproachParams = {
select?: string;
expand?: string;
};

export type GetApiV1GetApproachDtoIdParams = {
'api-version': string;
select?: string;
expand?: string;
};

export type PostApiV1UpsertApproachParams = {
'api-version': string;
select?: string;
expand?: string;
};

export type ApiVVersionApiVersionApproachKeyDetectorsCountParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export type ApiVVersionApiVersionApproachKeyDetectorsParams = {
select?: string;
filter?: string;
orderby?: string;
top?: number;
skip?: number;
count?: boolean;
};

export interface UtahUdotAtspmDataModelsWatchDogIgnoreEvent {
  /** @nullable */
  componentId?: number | null;
  componentType?: UtahUdotAtspmDataEnumsWatchDogComponentTypes;
  end?: string;
  id?: number;
  issueType?: UtahUdotAtspmDataEnumsWatchDogIssueTypes;
  location?: UtahUdotAtspmDataModelsLocation;
  locationId?: number;
  /** @nullable */
  locationIdentifier?: string | null;
  /** @nullable */
  phase?: number | null;
  start?: string;
}

export interface UtahUdotAtspmDataModelsVersionHistory {
  /** @nullable */
  children?: UtahUdotAtspmDataModelsVersionHistory[] | null;
  date?: string;
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  notes?: string | null;
  parent?: UtahUdotAtspmDataModelsVersionHistory;
  /** @nullable */
  parentId?: number | null;
  version?: number;
}

export interface UtahUdotAtspmDataModelsUserRegion {
  region?: UtahUdotAtspmDataModelsRegion;
  regionId?: number;
  /** @nullable */
  userId?: string | null;
}

export interface UtahUdotAtspmDataModelsUserJurisdiction {
  jurisdiction?: UtahUdotAtspmDataModelsJurisdiction;
  jurisdictionId?: number;
  /** @nullable */
  userId?: string | null;
}

export interface UtahUdotAtspmDataModelsUserArea {
  area?: UtahUdotAtspmDataModelsArea;
  areaId?: number;
  /** @nullable */
  userId?: string | null;
}

export interface UtahUdotAtspmDataModelsRouteDistance {
  distance?: number;
  id?: number;
  /** @nullable */
  locationIdentifierA?: string | null;
  /** @nullable */
  locationIdentifierB?: string | null;
  /** @nullable */
  nextLocations?: UtahUdotAtspmDataModelsRouteLocation[] | null;
  /** @nullable */
  previousLocations?: UtahUdotAtspmDataModelsRouteLocation[] | null;
}

export interface UtahUdotAtspmDataModelsRoute {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  routeLocations?: UtahUdotAtspmDataModelsRouteLocation[] | null;
}

export interface UtahUdotAtspmDataModelsRouteLocation {
  id?: number;
  isOpposingOverlap?: boolean;
  isPrimaryOverlap?: boolean;
  /** @nullable */
  locationIdentifier?: string | null;
  nextLocationDistance?: UtahUdotAtspmDataModelsRouteDistance;
  /** @nullable */
  nextLocationDistanceId?: number | null;
  opposingDirection?: UtahUdotAtspmDataModelsDirectionType;
  opposingDirectionId?: UtahUdotAtspmDataEnumsDirectionTypes;
  opposingPhase?: number;
  order?: number;
  previousLocationDistance?: UtahUdotAtspmDataModelsRouteDistance;
  /** @nullable */
  previousLocationDistanceId?: number | null;
  primaryDirection?: UtahUdotAtspmDataModelsDirectionType;
  primaryDirectionId?: UtahUdotAtspmDataEnumsDirectionTypes;
  primaryPhase?: number;
  route?: UtahUdotAtspmDataModelsRoute;
  routeId?: number;
}

export interface UtahUdotAtspmDataModelsRegion {
  /** @nullable */
  description?: string | null;
  id?: number;
  /** @nullable */
  locations?: UtahUdotAtspmDataModelsLocation[] | null;
  /** @nullable */
  userRegions?: UtahUdotAtspmDataModelsUserRegion[] | null;
}

export interface UtahUdotAtspmDataModelsProduct {
  id?: number;
  /** @nullable */
  manufacturer?: string | null;
  /** @nullable */
  model?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  webPage?: string | null;
}

export interface UtahUdotAtspmDataModelsMenuItem {
  /** @nullable */
  children?: UtahUdotAtspmDataModelsMenuItem[] | null;
  displayOrder?: number;
  /** @nullable */
  document?: string | null;
  /** @nullable */
  icon?: string | null;
  id?: number;
  /** @nullable */
  link?: string | null;
  /** @nullable */
  name?: string | null;
  parent?: UtahUdotAtspmDataModelsMenuItem;
  /** @nullable */
  parentId?: number | null;
}

export interface UtahUdotAtspmDataModelsMeasureOption {
  id?: number;
  measureType?: UtahUdotAtspmDataModelsMeasureType;
  measureTypeId?: number;
  /** @nullable */
  option?: string | null;
  /** @nullable */
  value?: string | null;
}

export interface UtahUdotAtspmDataModelsMeasureComment {
  /** @nullable */
  comment?: string | null;
  id?: number;
  /** @nullable */
  locationIdentifier?: string | null;
  /** @nullable */
  measureTypes?: UtahUdotAtspmDataModelsMeasureType[] | null;
  timeStamp?: string;
}

export interface UtahUdotAtspmDataModelsMeasureType {
  /** @nullable */
  abbreviation?: string | null;
  /** @nullable */
  detectionTypes?: UtahUdotAtspmDataModelsDetectionType[] | null;
  displayOrder?: number;
  id?: number;
  /** @nullable */
  measureComments?: UtahUdotAtspmDataModelsMeasureComment[] | null;
  /** @nullable */
  measureOptions?: UtahUdotAtspmDataModelsMeasureOption[] | null;
  /** @nullable */
  name?: string | null;
  showOnAggregationSite?: boolean;
  showOnWebsite?: boolean;
}

export interface UtahUdotAtspmDataModelsMapLayer {
  /** @nullable */
  createdBy?: string | null;
  createdOn?: string;
  /** @nullable */
  deletedBy?: string | null;
  /** @nullable */
  deletedOn?: string | null;
  id?: number;
  /** @nullable */
  mapLayerUrl?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  serviceType?: string | null;
  showByDefault?: boolean;
  /** @nullable */
  updatedBy?: string | null;
  updatedOn?: string;
}

export interface UtahUdotAtspmDataModelsJurisdiction {
  /** @nullable */
  countyParish?: string | null;
  id?: number;
  /** @nullable */
  locations?: UtahUdotAtspmDataModelsLocation[] | null;
  /** @nullable */
  mpo?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  otherPartners?: string | null;
  /** @nullable */
  userJurisdictions?: UtahUdotAtspmDataModelsUserJurisdiction[] | null;
}

export interface UtahUdotAtspmDataModelsDevice {
  deviceConfiguration?: UtahUdotAtspmDataModelsDeviceConfiguration;
  /** @nullable */
  deviceConfigurationId?: number | null;
  deviceStatus?: UtahUdotAtspmDataEnumsDeviceStatus;
  deviceType?: UtahUdotAtspmDataEnumsDeviceTypes;
  id?: number;
  /** @nullable */
  ipaddress?: string | null;
  location?: UtahUdotAtspmDataModelsLocation;
  locationId?: number;
  loggingEnabled?: boolean;
  /** @nullable */
  notes?: string | null;
}

export interface UtahUdotAtspmDataModelsLocation {
  /** @nullable */
  approaches?: UtahUdotAtspmDataModelsApproach[] | null;
  /** @nullable */
  areas?: UtahUdotAtspmDataModelsArea[] | null;
  chartEnabled?: boolean;
  /** @nullable */
  devices?: UtahUdotAtspmDataModelsDevice[] | null;
  id?: number;
  jurisdiction?: UtahUdotAtspmDataModelsJurisdiction;
  /** @nullable */
  jurisdictionId?: number | null;
  latitude?: number;
  /** @nullable */
  locationIdentifier?: string | null;
  locationType?: UtahUdotAtspmDataModelsLocationType;
  locationTypeId?: number;
  longitude?: number;
  /** @nullable */
  note?: string | null;
  pedsAre1to1?: boolean;
  /** @nullable */
  primaryName?: string | null;
  region?: UtahUdotAtspmDataModelsRegion;
  /** @nullable */
  regionId?: number | null;
  /** @nullable */
  secondaryName?: string | null;
  start?: string;
  versionAction?: UtahUdotAtspmDataEnumsLocationVersionActions;
}

export interface UtahUdotAtspmDataModelsLocationType {
  /** @nullable */
  icon?: string | null;
  id?: number;
  /** @nullable */
  locations?: UtahUdotAtspmDataModelsLocation[] | null;
  /** @nullable */
  name?: string | null;
}

export interface UtahUdotAtspmDataModelsFaq {
  /** @nullable */
  body?: string | null;
  displayOrder?: number;
  /** @nullable */
  header?: string | null;
  id?: number;
}

export interface UtahUdotAtspmDataModelsDirectionType {
  /** @nullable */
  abbreviation?: string | null;
  /** @nullable */
  approaches?: UtahUdotAtspmDataModelsApproach[] | null;
  /** @nullable */
  description?: string | null;
  displayOrder?: number;
  id?: UtahUdotAtspmDataEnumsDirectionTypes;
  /** @nullable */
  opposingDirections?: UtahUdotAtspmDataModelsRouteLocation[] | null;
  /** @nullable */
  primaryDirections?: UtahUdotAtspmDataModelsRouteLocation[] | null;
}

export interface UtahUdotAtspmDataModelsDeviceConfiguration {
  connectionTimeout?: number;
  /** @nullable */
  decoders?: string[] | null;
  /** @nullable */
  devices?: UtahUdotAtspmDataModelsDevice[] | null;
  /** @nullable */
  directory?: string | null;
  /** @nullable */
  firmware?: string | null;
  id?: number;
  /** @nullable */
  notes?: string | null;
  operationTimeout?: number;
  /** @nullable */
  password?: string | null;
  port?: number;
  product?: UtahUdotAtspmDataModelsProduct;
  /** @nullable */
  productId?: number | null;
  protocol?: UtahUdotAtspmDataEnumsTransportProtocols;
  /** @nullable */
  searchTerms?: string[] | null;
  /** @nullable */
  userName?: string | null;
}

export interface UtahUdotAtspmDataModelsDetectorComment {
  /** @nullable */
  comment?: string | null;
  detector?: UtahUdotAtspmDataModelsDetector;
  detectorId?: number;
  id?: number;
  timeStamp?: string;
}

export interface UtahUdotAtspmDataModelsDetectionType {
  /** @nullable */
  abbreviation?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  detectors?: UtahUdotAtspmDataModelsDetector[] | null;
  displayOrder?: number;
  id?: UtahUdotAtspmDataEnumsDetectionTypes;
  /** @nullable */
  measureTypes?: UtahUdotAtspmDataModelsMeasureType[] | null;
}

export interface UtahUdotAtspmDataModelsArea {
  id?: number;
  /** @nullable */
  locations?: UtahUdotAtspmDataModelsLocation[] | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  userAreas?: UtahUdotAtspmDataModelsUserArea[] | null;
}

export type UtahUdotAtspmDataEnumsWatchDogIssueTypes = typeof UtahUdotAtspmDataEnumsWatchDogIssueTypes[keyof typeof UtahUdotAtspmDataEnumsWatchDogIssueTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UtahUdotAtspmDataEnumsWatchDogIssueTypes = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
  NUMBER_7: 7,
} as const;

export type UtahUdotAtspmDataEnumsWatchDogComponentTypes = typeof UtahUdotAtspmDataEnumsWatchDogComponentTypes[keyof typeof UtahUdotAtspmDataEnumsWatchDogComponentTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UtahUdotAtspmDataEnumsWatchDogComponentTypes = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export type UtahUdotAtspmDataEnumsTransportProtocols = typeof UtahUdotAtspmDataEnumsTransportProtocols[keyof typeof UtahUdotAtspmDataEnumsTransportProtocols];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UtahUdotAtspmDataEnumsTransportProtocols = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;

export type UtahUdotAtspmDataEnumsMovementTypes = typeof UtahUdotAtspmDataEnumsMovementTypes[keyof typeof UtahUdotAtspmDataEnumsMovementTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UtahUdotAtspmDataEnumsMovementTypes = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
  NUMBER_7: 7,
} as const;

export type UtahUdotAtspmDataEnumsLocationVersionActions = typeof UtahUdotAtspmDataEnumsLocationVersionActions[keyof typeof UtahUdotAtspmDataEnumsLocationVersionActions];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UtahUdotAtspmDataEnumsLocationVersionActions = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_10: 10,
} as const;

export type UtahUdotAtspmDataEnumsLaneTypes = typeof UtahUdotAtspmDataEnumsLaneTypes[keyof typeof UtahUdotAtspmDataEnumsLaneTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UtahUdotAtspmDataEnumsLaneTypes = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
  NUMBER_7: 7,
} as const;

export type UtahUdotAtspmDataEnumsDirectionTypes = typeof UtahUdotAtspmDataEnumsDirectionTypes[keyof typeof UtahUdotAtspmDataEnumsDirectionTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UtahUdotAtspmDataEnumsDirectionTypes = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
  NUMBER_7: 7,
  NUMBER_8: 8,
} as const;

export interface UtahUdotAtspmDataModelsApproach {
  /** @nullable */
  description?: string | null;
  /** @nullable */
  detectors?: UtahUdotAtspmDataModelsDetector[] | null;
  directionType?: UtahUdotAtspmDataModelsDirectionType;
  directionTypeId?: UtahUdotAtspmDataEnumsDirectionTypes;
  id?: number;
  isPedestrianPhaseOverlap?: boolean;
  isPermissivePhaseOverlap?: boolean;
  isProtectedPhaseOverlap?: boolean;
  location?: UtahUdotAtspmDataModelsLocation;
  locationId?: number;
  /** @nullable */
  mph?: number | null;
  /** @nullable */
  pedestrianDetectors?: string | null;
  /** @nullable */
  pedestrianPhaseNumber?: number | null;
  /** @nullable */
  permissivePhaseNumber?: number | null;
  protectedPhaseNumber?: number;
}

export interface UtahUdotAtspmDataModelsDetector {
  approach?: UtahUdotAtspmDataModelsApproach;
  approachId?: number;
  dateAdded?: string;
  /** @nullable */
  dateDisabled?: string | null;
  /** @nullable */
  decisionPoint?: number | null;
  /** @nullable */
  dectectorIdentifier?: string | null;
  detectionHardware?: UtahUdotAtspmDataEnumsDetectionHardwareTypes;
  /** @nullable */
  detectionTypes?: UtahUdotAtspmDataModelsDetectionType[] | null;
  detectorChannel?: number;
  /** @nullable */
  detectorComments?: UtahUdotAtspmDataModelsDetectorComment[] | null;
  /** @nullable */
  distanceFromStopBar?: number | null;
  id?: number;
  /** @nullable */
  laneNumber?: number | null;
  laneType?: UtahUdotAtspmDataEnumsLaneTypes;
  latencyCorrection?: number;
  /** @nullable */
  minSpeedFilter?: number | null;
  /** @nullable */
  movementDelay?: number | null;
  movementType?: UtahUdotAtspmDataEnumsMovementTypes;
}

export type UtahUdotAtspmDataEnumsDeviceTypes = typeof UtahUdotAtspmDataEnumsDeviceTypes[keyof typeof UtahUdotAtspmDataEnumsDeviceTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UtahUdotAtspmDataEnumsDeviceTypes = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
} as const;

export type UtahUdotAtspmDataEnumsDeviceStatus = typeof UtahUdotAtspmDataEnumsDeviceStatus[keyof typeof UtahUdotAtspmDataEnumsDeviceStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UtahUdotAtspmDataEnumsDeviceStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
} as const;

export type UtahUdotAtspmDataEnumsDetectionTypes = typeof UtahUdotAtspmDataEnumsDetectionTypes[keyof typeof UtahUdotAtspmDataEnumsDetectionTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UtahUdotAtspmDataEnumsDetectionTypes = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
  NUMBER_7: 7,
  NUMBER_8: 8,
  NUMBER_9: 9,
  NUMBER_10: 10,
  NUMBER_11: 11,
} as const;

export type UtahUdotAtspmDataEnumsDetectionHardwareTypes = typeof UtahUdotAtspmDataEnumsDetectionHardwareTypes[keyof typeof UtahUdotAtspmDataEnumsDetectionHardwareTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UtahUdotAtspmDataEnumsDetectionHardwareTypes = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
} as const;

export interface UtahUdotAtspmConfigApiModelsSearchLocation {
  /** @nullable */
  areas?: number[] | null;
  chartEnabled?: boolean;
  /** @nullable */
  charts?: number[] | null;
  id?: number;
  /** @nullable */
  jurisdictionId?: number | null;
  latitude?: number;
  /** @nullable */
  locationIdentifier?: string | null;
  locationTypeId?: number;
  longitude?: number;
  /** @nullable */
  primaryName?: string | null;
  /** @nullable */
  regionId?: number | null;
  /** @nullable */
  secondaryName?: string | null;
  start?: string;
}

export interface UtahUdotAtspmConfigApiModelsRouteDto {
  /** @nullable */
  id?: number | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  routeLocations?: UtahUdotAtspmConfigApiModelsRouteLocationDto[] | null;
}

export interface UtahUdotAtspmConfigApiModelsRouteDistanceDto {
  distance?: number;
  id?: number;
  /** @nullable */
  locationIdentifierA?: string | null;
  /** @nullable */
  locationIdentifierB?: string | null;
}

export interface UtahUdotAtspmConfigApiModelsRouteDetectorDto {
  approachId?: number;
  dateAdded?: string;
  /** @nullable */
  dateDisabled?: string | null;
  /** @nullable */
  decisionPoint?: number | null;
  /** @nullable */
  dectectorIdentifier?: string | null;
  detectionHardware?: UtahUdotAtspmDataEnumsDetectionHardwareTypes;
  detectorChannel?: number;
  /** @nullable */
  distanceFromStopBar?: number | null;
  id?: number;
  /** @nullable */
  laneNumber?: number | null;
  laneType?: UtahUdotAtspmDataEnumsLaneTypes;
  latencyCorrection?: number;
  /** @nullable */
  minSpeedFilter?: number | null;
  /** @nullable */
  movementDelay?: number | null;
  movementType?: UtahUdotAtspmDataEnumsMovementTypes;
}

export interface UtahUdotAtspmConfigApiModelsRouteApproachDto {
  /** @nullable */
  description?: string | null;
  /** @nullable */
  detectors?: UtahUdotAtspmConfigApiModelsRouteDetectorDto[] | null;
  id?: number;
  isPedestrianPhaseOverlap?: boolean;
  isPermissivePhaseOverlap?: boolean;
  isProtectedPhaseOverlap?: boolean;
  locationId?: number;
  /** @nullable */
  mph?: number | null;
  /** @nullable */
  pedestrianDetectors?: string | null;
  /** @nullable */
  pedestrianPhaseNumber?: number | null;
  /** @nullable */
  permissivePhaseNumber?: number | null;
  protectedPhaseNumber?: number;
}

export interface UtahUdotAtspmConfigApiModelsRouteLocationDto {
  /** @nullable */
  approaches?: UtahUdotAtspmConfigApiModelsRouteApproachDto[] | null;
  id?: number;
  isOpposingOverlap?: boolean;
  isPrimaryOverlap?: boolean;
  latitude?: number;
  /** @nullable */
  locationId?: number | null;
  /** @nullable */
  locationIdentifier?: string | null;
  longitude?: number;
  nextLocationDistance?: UtahUdotAtspmConfigApiModelsRouteDistanceDto;
  /** @nullable */
  nextLocationDistanceId?: number | null;
  /** @nullable */
  opposingDirectionDescription?: string | null;
  opposingDirectionId?: number;
  opposingPhase?: number;
  order?: number;
  previousLocationDistance?: UtahUdotAtspmConfigApiModelsRouteDistanceDto;
  /** @nullable */
  previousLocationDistanceId?: number | null;
  /** @nullable */
  primaryDirectionDescription?: string | null;
  primaryDirectionId?: number;
  /** @nullable */
  primaryName?: string | null;
  primaryPhase?: number;
  routeId?: number;
  /** @nullable */
  secondaryName?: string | null;
}

export interface UtahUdotAtspmConfigApiModelsMeasureOptionDto {
  /** @nullable */
  id?: number | null;
  measureTypeId?: number;
  /** @nullable */
  option?: string | null;
  /** @nullable */
  value?: string | null;
}

export interface UtahUdotAtspmConfigApiModelsMeasureCommentsDto {
  /** @nullable */
  comment?: string | null;
  /** @nullable */
  id?: number | null;
  /** @nullable */
  locationIdentifier?: string | null;
  timeStamp?: string;
}

export interface UtahUdotAtspmConfigApiModelsMeasureTypeDto {
  /** @nullable */
  abbreviation?: string | null;
  displayOrder?: number;
  /** @nullable */
  id?: number | null;
  /** @nullable */
  measureComments?: UtahUdotAtspmConfigApiModelsMeasureCommentsDto[] | null;
  /** @nullable */
  measureOptions?: UtahUdotAtspmConfigApiModelsMeasureOptionDto[] | null;
  /** @nullable */
  name?: string | null;
  showOnAggregationSite?: boolean;
  showOnWebsite?: boolean;
}

export interface UtahUdotAtspmConfigApiModelsDetectionTypeDto {
  /** @nullable */
  abbreviation?: string | null;
  /** @nullable */
  description?: string | null;
  displayOrder?: number;
  id?: UtahUdotAtspmDataEnumsDetectionTypes;
  /** @nullable */
  measureTypes?: UtahUdotAtspmConfigApiModelsMeasureTypeDto[] | null;
}

export interface UtahUdotAtspmConfigApiModelsDetectorDto {
  /** @nullable */
  approachId?: number | null;
  dateAdded?: string;
  /** @nullable */
  dateDisabled?: string | null;
  /** @nullable */
  decisionPoint?: number | null;
  /** @nullable */
  dectectorIdentifier?: string | null;
  detectionHardware?: UtahUdotAtspmDataEnumsDetectionHardwareTypes;
  /** @nullable */
  detectionTypes?: UtahUdotAtspmConfigApiModelsDetectionTypeDto[] | null;
  detectorChannel?: number;
  /** @nullable */
  distanceFromStopBar?: number | null;
  /** @nullable */
  id?: number | null;
  /** @nullable */
  laneNumber?: number | null;
  laneType?: UtahUdotAtspmDataEnumsLaneTypes;
  latencyCorrection?: number;
  /** @nullable */
  minSpeedFilter?: number | null;
  /** @nullable */
  movementDelay?: number | null;
  movementType?: UtahUdotAtspmDataEnumsMovementTypes;
}

export interface UtahUdotAtspmConfigApiModelsApproachDto {
  /** @nullable */
  description?: string | null;
  /** @nullable */
  detectors?: UtahUdotAtspmConfigApiModelsDetectorDto[] | null;
  directionTypeId?: UtahUdotAtspmDataEnumsDirectionTypes;
  /** @nullable */
  id?: number | null;
  isPedestrianPhaseOverlap?: boolean;
  isPermissivePhaseOverlap?: boolean;
  isProtectedPhaseOverlap?: boolean;
  locationId?: number;
  /** @nullable */
  mph?: number | null;
  /** @nullable */
  pedestrianDetectors?: string | null;
  /** @nullable */
  pedestrianPhaseNumber?: number | null;
  /** @nullable */
  permissivePhaseNumber?: number | null;
  protectedPhaseNumber?: number;
}

export interface UtahUdotAtspmBusinessWatchdogDetectionTypeGroup {
  count?: number;
  /** @nullable */
  id?: string | null;
}

export interface UtahUdotATSPMConfigApiModelsDeviceGroup {
  count?: number;
  /** @nullable */
  firmware?: string | null;
  /** @nullable */
  manufacturer?: string | null;
  /** @nullable */
  model?: string | null;
}

export interface LocationDefaultLocationSaveTemplatedLocationParameters {
  /** @nullable */
  devices?: UtahUdotAtspmDataModelsDevice[] | null;
  latitude: number;
  longitude: number;
  /** @nullable */
  note?: string | null;
  /** @nullable */
  primaryName?: string | null;
  /** @nullable */
  secondaryName?: string | null;
}

