#region license
// Copyright 2026 Utah Departement of Transportation
// for Infrastructure - Utah.Udot.Atspm.Infrastructure.Services.HostedServices/DeviceEventLogHostedService.cs
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
// http://www.apache.org/licenses/LICENSE-2.
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#endregion

using Lextm.SharpSnmpLib.Messaging;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Diagnostics;
using System.Threading.Tasks.Dataflow;
using Utah.Udot.Atspm.Infrastructure.Extensions;
using Utah.Udot.ATSPM.Infrastructure.Workflows;
using Utah.Udot.NetStandardToolkit.Workflows;

namespace Utah.Udot.Atspm.Infrastructure.Services.HostedServices
{
    /// <summary>
    /// Hosted service for running the <see cref="DeviceEventLogWorkflow"/>
    /// </summary>
    /// <remarks>
    /// Hosted service for running the <see cref="DeviceEventLogWorkflow"/>
    /// </remarks>
    /// <param name="log"></param>
    /// <param name="serviceProvider"></param>
    /// <param name="options"></param>
    public class DeviceEventLogHostedService(ILogger<DeviceEventLogHostedService> log, IServiceScopeFactory serviceProvider, IOptions<DeviceEventLoggingConfiguration> options) : HostedServiceBase(log, serviceProvider)
    {
        private readonly IOptions<DeviceEventLoggingConfiguration> _options = options;

        ///// <inheritdoc/>
        //public override async Task Process(IServiceScope scope, Stopwatch stopwatch, CancellationToken cancellationToken = default)
        //{
        //    var repo = scope.ServiceProvider.GetService<IDeviceRepository>();

        //    var workflow = new DeviceEventLogWorkflow(scope.ServiceProvider.GetService<IServiceScopeFactory>(), _options.Value.BatchSize, _options.Value.ParallelProcesses, cancellationToken);

        //    await workflow.WhenInitialized();

        //    await foreach (var d in repo.GetDevicesForLogging(_options.Value.DeviceEventLoggingQueryOptions))
        //    {
        //        await workflow.Input.SendAsync(d);
        //    }

        //    workflow.Input.Complete();

        //    await Task.WhenAll(workflow.Steps.Select(s => s.Completion));
        //}

        /// <inheritdoc/>
        public override async Task Process(IServiceScope scope, Stopwatch stopwatch, CancellationToken cancellationToken = default)
        {
            var repo = scope.ServiceProvider.GetService<IDeviceRepository>();
            var scopeFactory = scope.ServiceProvider.GetService<IServiceScopeFactory>();

            var devices = repo.GetDevicesForLogging(_options.Value.DeviceEventLoggingQueryOptions);
            var total = await devices.CountAsync(cancellationToken);

            int targetInstances = 20;
            int devicesPerWorkflow = (int)Math.Ceiling((double)total / targetInstances);
            int actualInstances = total < targetInstances ? total : targetInstances;

            Func<DeviceEventLogWorkflow> workflowFactory = () => new DeviceEventLogWorkflow(scopeFactory, _options.Value.BatchSize, _options.Value.ParallelProcesses, cancellationToken);

            await workflowFactory.BatchRunAsync(devices, devicesPerWorkflow, actualInstances, cancellationToken);
        }
    }

    public static class Testing
    {
        /// <summary>
        /// Executes multiple isolated instances of a workflow in parallel by chunking the input source into batches.
        /// </summary>
        /// <typeparam name="TInput">The type of the input data items to be processed.</typeparam>
        /// <typeparam name="TOutput">The type of the output data generated by the workflow.</typeparam>
        /// <param name="factory">A delegate factory used to instantiate a fresh, isolated workflow for each parallel batch.</param>
        /// <param name="source">An asynchronous stream of input data items.</param>
        /// <param name="batchSize">The number of items to include in each chunk/batch.</param>
        /// <param name="parallelInstances">The maximum number of workflow instances to run concurrently.</param>
        /// <param name="cancellationToken">A token to monitor for cancellation requests.</param>
        /// <returns>A task that represents the completion of all batches across all workflow instances.</returns>
        /// <remarks>
        /// This method uses a <see cref="BatchBlock{T}"/> to group items and an <see cref="ActionBlock{TInput}"/> 
        /// to manage the parallel workflow lifecycle. It includes a polling mechanism to ensure the workflow 
        /// base class has completed its background initialization before data is sent to the input block.
        /// </remarks>
        public static async Task BatchRunAsync<TInput, TOutput>(
            this Func<WorkflowBase<TInput, TOutput>> factory,
            IAsyncEnumerable<TInput> source,
            int batchSize,
            int parallelInstances,
            CancellationToken cancellationToken)
        {
            var batcher = new BatchBlock<TInput>(batchSize, new GroupingDataflowBlockOptions
            {
                BoundedCapacity = batchSize * (parallelInstances + 2),
                CancellationToken = cancellationToken
            });

            var manager = new ActionBlock<TInput[]>(async chunk =>
            {
                using var workflow = factory();

                #region Remove when base services are fixed

                int attempts = 0;
                while (workflow.Input == null && attempts < 150)
                {
                    await Task.Delay(50, cancellationToken);
                    attempts++;
                }

                attempts = 0;
                while (!workflow.IsInitialized && attempts < 150)
                {
                    await Task.Delay(50, cancellationToken);
                    attempts++;
                }


                if (workflow.Input == null)
                {
                    // Throwing here will still fault the block, but at least 
                    // you'll see WHY in the logs instead of a silent hang.
                    Console.WriteLine("Base service failed to initialize workflow.Input in 7.5s.");
                    return;
                }

                #endregion

                foreach (var item in chunk)
                {
                    await workflow.Input.SendAsync(item, cancellationToken);
                }

                workflow.Input.Complete();
                await Task.WhenAll(workflow.Steps.Select(s => s.Completion));
            },
            new ExecutionDataflowBlockOptions
            {
                MaxDegreeOfParallelism = parallelInstances,
                BoundedCapacity = parallelInstances + 1,
                CancellationToken = cancellationToken
            });

            batcher.LinkTo(manager, new DataflowLinkOptions { PropagateCompletion = true });

            await foreach (var item in source.WithCancellation(cancellationToken))
            {
                await batcher.SendAsync(item, cancellationToken);
            }

            batcher.Complete();
            await manager.Completion;

            Console.WriteLine($"-------------------------done!");
        }
    }
}