// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ATSPM.Data.Interfaces;
using System;
using System.Collections.Generic;

namespace ATSPM.Data.Models
{
    public partial class ApproachPcdAggregation : ATSPMAggregationBase, ISignalPhaseLayer
    {
        public string SignalIdentifier { get; set; }
        public int PhaseNumber { get; set; }
        public int ApproachId { get; set; }
        public bool IsProtectedPhase { get; set; }
        public int ArrivalsOnGreen { get; set; }
        public int ArrivalsOnRed { get; set; }
        public int ArrivalsOnYellow { get; set; }
        public int Volume { get; set; }
        public int TotalDelay { get; set; }
    }
}