// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATSPM.Data.Models
{
    public partial class ControllerType
    {
        public ControllerType()
        {
            Signals = new HashSet<Signal>();
        }

        public int ControllerTypeID { get; set; }
        public string Description { get; set; }
        public long Snmpport { get; set; }
        public string Ftpdirectory { get; set; }
        public bool ActiveFtp { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Signal> Signals { get; set; }
    }
}