// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATSPM.Data.Models
{
    public partial class DatabaseArchiveExcludedSignal
    {
        public int ID { get; set; }
        public string SignalID { get; set; }
    }
}