// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ATSPM.Data.Relationships;

namespace ATSPM.Data.Models
{
    /// <summary>
    /// Jurisdiction
    /// </summary>
    public partial class Jurisdiction : AtspmConfigModelBase<int>, IRelatedLocations
    {
        /// <summary>
        /// Name of jurisdiction
        /// </summary>
        public string Name { get; set; }
        
        //TODO: What is this?
        /// <summary>
        /// Mpo
        /// </summary>
        public string Mpo { get; set; }
        
        /// <summary>
        /// Jurisdiction county or parish
        /// </summary>
        public string CountyParish { get; set; }
        
        /// <summary>
        /// Other partners
        /// </summary>
        public string OtherPartners { get; set; }

        public virtual ICollection<UserJurisdiction> UserJurisdictions { get; set; } = new HashSet<UserJurisdiction>();

        #region IRelatedLocations

        /// <inheritdoc/>
        public virtual ICollection<Location> Locations { get; set; } = new HashSet<Location>();

        #endregion

        /// <inheritdoc/>
        public override string ToString() => $"{Id} - {Name}";
    }
}