// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATSPM.Data.Models
{
    public partial class MetricTypes
    {
        public MetricTypes()
        {
            ActionLog_ActionLog = new HashSet<ActionLogs>();
            DetectionType_DetectionType = new HashSet<DetectionTypes>();
            MetricComment_Comment = new HashSet<MetricComments>();
        }

        public int MetricID { get; set; }
        public string ChartName { get; set; }
        public string Abbreviation { get; set; }
        public bool ShowOnWebsite { get; set; }
        public bool ShowOnAggregationSite { get; set; }
        public int DisplayOrder { get; set; }

        public virtual ICollection<ActionLogs> ActionLog_ActionLog { get; set; }
        public virtual ICollection<DetectionTypes> DetectionType_DetectionType { get; set; }
        public virtual ICollection<MetricComments> MetricComment_Comment { get; set; }
    }
}