// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATSPM.Data.Models
{
    public partial class Routes
    {
        public Routes()
        {
            RouteSignals = new HashSet<RouteSignals>();
        }

        public int Id { get; set; }
        public string RouteName { get; set; }

        public virtual ICollection<RouteSignals> RouteSignals { get; set; }
    }
}