// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ATSPM.Data.Models
{
    public partial class Signal : ATSPMModelBase
    {
        public Signal()
        {
            Areas = new HashSet<Area>();
        }

        public string SignalId { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string PrimaryName { get; set; }
        public string SecondaryName { get; set; }
        public string Ipaddress { get; set; }
        public int RegionId { get; set; }
        public int ControllerTypeId { get; set; }
        public bool Enabled { get; set; }
        public int VersionId { get; set; }
        public int VersionActionId { get; set; }
        public string Note { get; set; }
        public DateTime Start { get; set; }
        public int JurisdictionId { get; set; }
        public bool Pedsare1to1 { get; set; }

        public virtual ControllerType ControllerType { get; set; }
        public virtual Jurisdiction Jurisdiction { get; set; }
        public virtual Region Region { get; set; }
        public virtual VersionAction VersionAction { get; set; }

        public virtual ICollection<Area> Areas { get; set; }
    }
}