// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ATSPM.Data.Interfaces;
using ATSPM.Domain.Common;
using System;
using System.Collections.Generic;

namespace ATSPM.Data.Models
{
    public partial class SignalPlanAggregation : ATSPMAggregationBase, ISignalLayer, IPlanLayer
    {
        public string SignalIdentifier { get; set; }
        public DateTime Start { get; set; }
        public DateTime End { get; set; }
        public int PlanNumber { get; set; }
    }
}