// <auto-generated />
using System;
using ATSPM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ATSPM.Infrastructure.Migrations.LegacyEventLog
{
    [DbContext(typeof(LegacyEventLogContext))]
    [Migration("20230111191143_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ATSPM.Data.Models.ControllerEventLog", b =>
                {
                    b.Property<string>("SignalId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SignalID");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventCode")
                        .HasColumnType("int");

                    b.Property<int>("EventParam")
                        .HasColumnType("int");

                    b.HasKey("SignalId", "Timestamp", "EventCode", "EventParam");

                    b.ToTable("Controller_Event_Log", null, t =>
                        {
                            t.HasComment("Old Log Data Table");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
