/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * ATSPM Speed Management Api
 * ATSPM Log Data with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
export type PostApiViolationsAndExtremeViolationsGetReportDataParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1SpeedViolationsGetReportDataParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1SpeedVariabilityGetReportDataParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1SpeedOverTimeGetReportDataParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1SpeedOverDistanceGetReportDataParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetRouteSpeedsParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1SpeedFromImpactSegmentSegmentIdParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1SpeedFromImpactImpactImpactIdParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1SpeedComplianceGetReportDataParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1SegmentSegmentIdSpeedsParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1SegmentSpeedsParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1SegmentSegmentIdParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1SegmentAllSegmentsParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1SegmentParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1SegmentParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1RegionParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1MonthlyAggregationSpeedCategoryFiltersParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1MonthlyAggregationMonthAggClassificationsParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1MonthlyAggregationFilteringTimePeriodsParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1MonthlyAggregationSegmentsSegmentIdMonthAggClassificationTimePeriodParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1MonthlyAggregationSegmentParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1MonthlyAggregationSourceSourceIdParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1MonthlyAggregationHotspotsParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1MonthlyAggregationLatestMonthAggClassificationTimePeriodParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type DeleteApiV1MonthlyAggregationParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1MonthlyAggregationParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type DeleteApiV1ImpactTypeIdParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PutApiV1ImpactTypeIdParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1ImpactTypeIdParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1ImpactTypeParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1ImpactTypeParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type DeleteApiV1ImpactIdImpactTypeImpactTypeIdParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PutApiV1ImpactIdImpactTypeImpactTypeIdParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type DeleteApiV1ImpactIdSegmentsSegmentIdParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PutApiV1ImpactIdSegmentsSegmentIdParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type DeleteApiV1ImpactIdParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PutApiV1ImpactIdParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1ImpactIdParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1ImpactParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1ImpactParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1FunctionalTypeParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1EffectivenessOfStrategiesGetReportDataParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1DataQualityGetReportDataParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1CountyParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type PostApiV1CongestionTrackingGetReportDataParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1CityParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export type GetApiV1AccessCategoryParams = {
/**
 * The requested API version
 */
'api-version'?: string;
};

export interface ViolationsAndExtremeViolationsOptions {
  endDate?: string;
  segmentIds?: string[] | null;
  startDate?: string;
}

export interface ViolationsAndExtremeViolationsDto {
  endingMilePoint?: number;
  exteremeViolations?: number;
  flow?: number;
  segmentId?: string;
  segmentName?: string | null;
  speedLimit?: number;
  startingMilePoint?: number;
  time?: string;
  violations?: number;
}

export interface TimeSegmentEffectiveness {
  averageEightyFifthSpeed?: number;
  averageSpeed?: number;
  endDate?: string;
  flow?: number;
  maxSpeed?: number;
  minSpeed?: number;
  percentExtremeViolations?: number;
  percentViolations?: number;
  startDate?: string;
  variability?: number;
}

export type TimePeriodFilter = typeof TimePeriodFilter[keyof typeof TimePeriodFilter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimePeriodFilter = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
} as const;

export type TimeOptionsEnum = typeof TimeOptionsEnum[keyof typeof TimeOptionsEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimeOptionsEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export interface SpeedViolationsOptions {
  dayOfWeek?: number | null;
  endDate?: string;
  endTime?: string | null;
  segmentIds?: string[] | null;
  specificDays?: string[] | null;
  startDate?: string;
  startTime?: string | null;
}

export interface SpeedViolationsDto {
  dailySpeedViolationsDto?: DailySpeedViolationsDto[] | null;
  percentExtremeViolations?: number;
  percentViolations?: number;
  segmentId?: string;
  segmentName?: string | null;
  speedLimit?: number;
  totalExtremeViolationsCount?: number;
  totalFlow?: number;
  totalViolationsCount?: number;
}

export interface SpeedVariabilityOptions {
  daysOfWeek?: DayOfWeek[] | null;
  endDate?: string;
  isHolidaysFiltered?: boolean | null;
  segmentId?: string | null;
  sourceId?: number;
  startDate?: string;
}

export interface SpeedVariabilityDataDto {
  avgSpeed?: number;
  date?: string;
  maxSpeed?: number;
  minSpeed?: number;
  speedVariability?: number;
}

export interface SpeedVariabilityDto {
  data?: SpeedVariabilityDataDto[] | null;
  endDate?: string;
  endingMilePoint?: number;
  segmentId?: string;
  segmentName?: string | null;
  speedLimit?: number;
  startDate?: string;
  startingMilePoint?: number;
}

export interface SpeedOverTimeOptions {
  endDate?: string;
  endTime?: string | null;
  monthAggClassification?: MonthAggClassification;
  segmentId?: string | null;
  sourceId?: number;
  startDate?: string;
  startTime?: string | null;
  timeOptions?: TimeOptionsEnum;
  timePeriod?: TimePeriodFilter;
}

export interface SpeedOverDistanceOptions {
  endDate?: string;
  monthAggClassification?: MonthAggClassification;
  segmentIds?: string[] | null;
  startDate?: string;
  timePeriod?: TimePeriodFilter;
}

export interface SpeedOverDistanceDto {
  average?: number;
  eightyFifth?: number;
  endDate?: string;
  endingMilePoint?: number;
  segmentId?: string;
  segmentName?: string | null;
  speedLimit?: number;
  startDate?: string;
  startingMilePoint?: number;
}

export interface SpeedDataDto {
  date?: string;
  series?: AverageAndEightyFifthSeriesData;
}

export interface SpeedOverTimeDto {
  data?: SpeedDataDto[] | null;
  endDate?: string;
  endingMilePoint?: number;
  segmentId?: string;
  segmentName?: string | null;
  speedLimit?: number;
  startDate?: string;
  startingMilePoint?: number;
  timeOptions?: TimeOptionsEnum;
}

export interface SpeedComplianceOptions {
  endDate?: string;
  segmentIds?: string[] | null;
  startDate?: string;
}

export interface SpeedComplianceDto {
  average?: number;
  avgVsBaseSpeed?: number;
  eightyFifth?: number;
  eightyFifthPercentileVsBaseSpeed?: number;
  endDate?: string;
  endingMilePoint?: number;
  segmentId?: string;
  segmentName?: string | null;
  speedLimit?: number;
  startDate?: string;
  startingMilePoint?: number;
}

export type SpeedCategoryFilter = typeof SpeedCategoryFilter[keyof typeof SpeedCategoryFilter];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SpeedCategoryFilter = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
  NUMBER_7: 7,
  NUMBER_8: 8,
  NUMBER_9: 9,
  NUMBER_10: 10,
  NUMBER_11: 11,
  NUMBER_12: 12,
} as const;

export interface SegmentRequestDto {
  endDate?: string;
  segmentIds?: string[] | null;
  sourceIds?: number[] | null;
  startDate?: string;
}

export interface Segment {
  accessCategory?: string | null;
  alternateIdentifier?: string | null;
  city?: string | null;
  county?: string | null;
  direction?: string | null;
  endMilePoint?: number;
  entities?: SegmentEntity[] | null;
  functionalType?: string | null;
  id?: string;
  name?: string | null;
  offset?: number | null;
  region?: string | null;
  shape?: Geometry;
  shapeWKT?: string | null;
  speedLimit?: number;
  startMilePoint?: number;
  udotRouteNumber?: string | null;
}

export interface SpeedFromImpactDto {
  endDate?: string;
  hourlySpeeds?: HourlySpeed[] | null;
  impacts?: Impact[] | null;
  segments?: Segment[] | null;
  startDate?: string;
}

export interface SegmentEntity {
  entityId?: number;
  entityType?: string | null;
  length?: number;
  segment?: Segment;
  segmentId?: string;
  sourceId?: number;
}

export interface ProblemDetails {
  detail?: string | null;
  instance?: string | null;
  status?: number | null;
  title?: string | null;
  type?: string | null;
  [key: string]: unknown;
}

export type PrecisionModels = typeof PrecisionModels[keyof typeof PrecisionModels];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PrecisionModels = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export interface PrecisionModel {
  readonly gridSize?: number;
  readonly isFloating?: boolean;
  readonly maximumSignificantDigits?: number;
  precisionModelType?: PrecisionModels;
  scale?: number;
}

export type PointUserData = unknown | null;

export type Ordinates = typeof Ordinates[keyof typeof Ordinates];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Ordinates = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_7: 7,
  NUMBER_8: 8,
  NUMBER_16: 16,
  NUMBER_32: 32,
  NUMBER_64: 64,
  NUMBER_128: 128,
  NUMBER_256: 256,
  NUMBER_512: 512,
  NUMBER_1024: 1024,
  NUMBER_2048: 2048,
  NUMBER_4096: 4096,
  NUMBER_8192: 8192,
  NUMBER_16384: 16384,
  NUMBER_32768: 32768,
  NUMBER_65535: 65535,
  NUMBER_65536: 65536,
  NUMBER_65539: 65539,
  NUMBER_65543: 65543,
  NUMBER_131072: 131072,
  NUMBER_262144: 262144,
  NUMBER_524288: 524288,
  NUMBER_1048576: 1048576,
  NUMBER_2097152: 2097152,
  NUMBER_4194304: 4194304,
  NUMBER_8388608: 8388608,
  NUMBER_16777216: 16777216,
  NUMBER_33554432: 33554432,
  NUMBER_67108864: 67108864,
  NUMBER_134217728: 134217728,
  NUMBER_268435456: 268435456,
  NUMBER_536870912: 536870912,
  NUMBER_1073741824: 1073741824,
  NUMBER_MINUS_2147483648: -2147483648,
  NUMBER_MINUS_65536: -65536,
  NUMBER_MINUS_1: -1,
} as const;

export type OgcGeometryType = typeof OgcGeometryType[keyof typeof OgcGeometryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OgcGeometryType = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
  NUMBER_7: 7,
  NUMBER_8: 8,
  NUMBER_9: 9,
  NUMBER_10: 10,
  NUMBER_11: 11,
  NUMBER_12: 12,
  NUMBER_13: 13,
  NUMBER_14: 14,
  NUMBER_15: 15,
  NUMBER_16: 16,
} as const;

export interface NtsGeometryServices {
  coordinateEqualityComparer?: CoordinateEqualityComparer;
  defaultCoordinateSequenceFactory?: CoordinateSequenceFactory;
  defaultPrecisionModel?: PrecisionModel;
  readonly defaultSRID?: number;
  geometryOverlay?: GeometryOverlay;
}

export interface NameAndIdDto {
  id?: string;
  name?: string | null;
}

export interface MonthlyAggregation {
  allDayAverageEightyFifthSpeed?: number | null;
  allDayAverageSpeed?: number | null;
  allDayAvgSpeedVsSpeedLimit?: number | null;
  allDayEightyFifthSpeedVsSpeedLimit?: number | null;
  allDayExtremeViolations?: number | null;
  allDayFlow?: number | null;
  allDayMaxSpeed?: number | null;
  allDayMinSpeed?: number | null;
  allDayPercentExtremeViolations?: number | null;
  allDayPercentObserved?: number | null;
  allDayPercentViolations?: number | null;
  allDayVariability?: number | null;
  allDayViolations?: number | null;
  amPeakAverageEightyFifthSpeed?: number | null;
  amPeakAverageSpeed?: number | null;
  amPeakAvgSpeedVsSpeedLimit?: number | null;
  amPeakEightyFifthSpeedVsSpeedLimit?: number | null;
  amPeakExtremeViolations?: number | null;
  amPeakFlow?: number | null;
  amPeakMaxSpeed?: number | null;
  amPeakMinSpeed?: number | null;
  amPeakPercentExtremeViolations?: number | null;
  amPeakPercentObserved?: number | null;
  amPeakPercentViolations?: number | null;
  amPeakVariability?: number | null;
  amPeakViolations?: number | null;
  binStartTime?: string;
  createdDate?: string | null;
  earlyMorningAverageEightyFifthSpeed?: number | null;
  earlyMorningAverageSpeed?: number | null;
  earlyMorningAvgSpeedVsSpeedLimit?: number | null;
  earlyMorningEightyFifthSpeedVsSpeedLimit?: number | null;
  earlyMorningExtremeViolations?: number | null;
  earlyMorningFlow?: number | null;
  earlyMorningMaxSpeed?: number | null;
  earlyMorningMinSpeed?: number | null;
  earlyMorningPercentExtremeViolations?: number | null;
  earlyMorningPercentObserved?: number | null;
  earlyMorningPercentViolations?: number | null;
  earlyMorningVariability?: number | null;
  earlyMorningViolations?: number | null;
  eveningAverageEightyFifthSpeed?: number | null;
  eveningAverageSpeed?: number | null;
  eveningAvgSpeedVsSpeedLimit?: number | null;
  eveningEightyFifthSpeedVsSpeedLimit?: number | null;
  eveningExtremeViolations?: number | null;
  eveningFlow?: number | null;
  eveningMaxSpeed?: number | null;
  eveningMinSpeed?: number | null;
  eveningPercentExtremeViolations?: number | null;
  eveningPercentObserved?: number | null;
  eveningPercentViolations?: number | null;
  eveningVariability?: number | null;
  eveningViolations?: number | null;
  id?: string | null;
  midDayAverageEightyFifthSpeed?: number | null;
  midDayAverageSpeed?: number | null;
  midDayAvgSpeedVsSpeedLimit?: number | null;
  midDayEightyFifthSpeedVsSpeedLimit?: number | null;
  midDayExtremeViolations?: number | null;
  midDayFlow?: number | null;
  midDayMaxSpeed?: number | null;
  midDayMinSpeed?: number | null;
  midDayPercentExtremeViolations?: number | null;
  midDayPercentObserved?: number | null;
  midDayPercentViolations?: number | null;
  midDayVariability?: number | null;
  midDayViolations?: number | null;
  offPeakAverageEightyFifthSpeed?: number | null;
  offPeakAverageSpeed?: number | null;
  offPeakAvgSpeedVsSpeedLimit?: number | null;
  offPeakEightyFifthSpeedVsSpeedLimit?: number | null;
  offPeakExtremeViolations?: number | null;
  offPeakFlow?: number | null;
  offPeakMaxSpeed?: number | null;
  offPeakMinSpeed?: number | null;
  offPeakPercentExtremeViolations?: number | null;
  offPeakPercentObserved?: number | null;
  offPeakPercentViolations?: number | null;
  offPeakVariability?: number | null;
  offPeakViolations?: number | null;
  pmPeakAverageEightyFifthSpeed?: number | null;
  pmPeakAverageSpeed?: number | null;
  pmPeakAvgSpeedVsSpeedLimit?: number | null;
  pmPeakEightyFifthSpeedVsSpeedLimit?: number | null;
  pmPeakExtremeViolations?: number | null;
  pmPeakFlow?: number | null;
  pmPeakMaxSpeed?: number | null;
  pmPeakMinSpeed?: number | null;
  pmPeakPercentExtremeViolations?: number | null;
  pmPeakPercentObserved?: number | null;
  pmPeakPercentViolations?: number | null;
  pmPeakVariability?: number | null;
  pmPeakViolations?: number | null;
  segmentId?: string;
  sourceId?: number;
  weekdayAllDayAverageEightyFifthSpeed?: number | null;
  weekdayAllDayAverageSpeed?: number | null;
  weekdayAllDayAvgSpeedVsSpeedLimit?: number | null;
  weekdayAllDayEightyFifthSpeedVsSpeedLimit?: number | null;
  weekdayAllDayExtremeViolations?: number | null;
  weekdayAllDayFlow?: number | null;
  weekdayAllDayMaxSpeed?: number | null;
  weekdayAllDayMinSpeed?: number | null;
  weekdayAllDayPercentExtremeViolations?: number | null;
  weekdayAllDayPercentObserved?: number | null;
  weekdayAllDayPercentViolations?: number | null;
  weekdayAllDayVariability?: number | null;
  weekdayAllDayViolations?: number | null;
  weekdayAmPeakAverageEightyFifthSpeed?: number | null;
  weekdayAmPeakAverageSpeed?: number | null;
  weekdayAmPeakAvgSpeedVsSpeedLimit?: number | null;
  weekdayAmPeakEightyFifthSpeedVsSpeedLimit?: number | null;
  weekdayAmPeakExtremeViolations?: number | null;
  weekdayAmPeakFlow?: number | null;
  weekdayAmPeakMaxSpeed?: number | null;
  weekdayAmPeakMinSpeed?: number | null;
  weekdayAmPeakPercentExtremeViolations?: number | null;
  weekdayAmPeakPercentObserved?: number | null;
  weekdayAmPeakPercentViolations?: number | null;
  weekdayAmPeakVariability?: number | null;
  weekdayAmPeakViolations?: number | null;
  weekdayEarlyMorningAverageEightyFifthSpeed?: number | null;
  weekdayEarlyMorningAverageSpeed?: number | null;
  weekdayEarlyMorningAvgSpeedVsSpeedLimit?: number | null;
  weekdayEarlyMorningEightyFifthSpeedVsSpeedLimit?: number | null;
  weekdayEarlyMorningExtremeViolations?: number | null;
  weekdayEarlyMorningFlow?: number | null;
  weekdayEarlyMorningMaxSpeed?: number | null;
  weekdayEarlyMorningMinSpeed?: number | null;
  weekdayEarlyMorningPercentExtremeViolations?: number | null;
  weekdayEarlyMorningPercentObserved?: number | null;
  weekdayEarlyMorningPercentViolations?: number | null;
  weekdayEarlyMorningVariability?: number | null;
  weekdayEarlyMorningViolations?: number | null;
  weekdayEveningAverageEightyFifthSpeed?: number | null;
  weekdayEveningAverageSpeed?: number | null;
  weekdayEveningAvgSpeedVsSpeedLimit?: number | null;
  weekdayEveningEightyFifthSpeedVsSpeedLimit?: number | null;
  weekdayEveningExtremeViolations?: number | null;
  weekdayEveningFlow?: number | null;
  weekdayEveningMaxSpeed?: number | null;
  weekdayEveningMinSpeed?: number | null;
  weekdayEveningPercentExtremeViolations?: number | null;
  weekdayEveningPercentObserved?: number | null;
  weekdayEveningPercentViolations?: number | null;
  weekdayEveningVariability?: number | null;
  weekdayEveningViolations?: number | null;
  weekdayMidDayAverageEightyFifthSpeed?: number | null;
  weekdayMidDayAverageSpeed?: number | null;
  weekdayMidDayAvgSpeedVsSpeedLimit?: number | null;
  weekdayMidDayEightyFifthSpeedVsSpeedLimit?: number | null;
  weekdayMidDayExtremeViolations?: number | null;
  weekdayMidDayFlow?: number | null;
  weekdayMidDayMaxSpeed?: number | null;
  weekdayMidDayMinSpeed?: number | null;
  weekdayMidDayPercentExtremeViolations?: number | null;
  weekdayMidDayPercentObserved?: number | null;
  weekdayMidDayPercentViolations?: number | null;
  weekdayMidDayVariability?: number | null;
  weekdayMidDayViolations?: number | null;
  weekdayOffPeakAverageEightyFifthSpeed?: number | null;
  weekdayOffPeakAverageSpeed?: number | null;
  weekdayOffPeakAvgSpeedVsSpeedLimit?: number | null;
  weekdayOffPeakEightyFifthSpeedVsSpeedLimit?: number | null;
  weekdayOffPeakExtremeViolations?: number | null;
  weekdayOffPeakFlow?: number | null;
  weekdayOffPeakMaxSpeed?: number | null;
  weekdayOffPeakMinSpeed?: number | null;
  weekdayOffPeakPercentExtremeViolations?: number | null;
  weekdayOffPeakPercentObserved?: number | null;
  weekdayOffPeakPercentViolations?: number | null;
  weekdayOffPeakVariability?: number | null;
  weekdayOffPeakViolations?: number | null;
  weekdayPmPeakAverageEightyFifthSpeed?: number | null;
  weekdayPmPeakAverageSpeed?: number | null;
  weekdayPmPeakAvgSpeedVsSpeedLimit?: number | null;
  weekdayPmPeakEightyFifthSpeedVsSpeedLimit?: number | null;
  weekdayPmPeakExtremeViolations?: number | null;
  weekdayPmPeakFlow?: number | null;
  weekdayPmPeakMaxSpeed?: number | null;
  weekdayPmPeakMinSpeed?: number | null;
  weekdayPmPeakPercentExtremeViolations?: number | null;
  weekdayPmPeakPercentObserved?: number | null;
  weekdayPmPeakPercentViolations?: number | null;
  weekdayPmPeakVariability?: number | null;
  weekdayPmPeakViolations?: number | null;
  weekendAllDayAverageEightyFifthSpeed?: number | null;
  weekendAllDayAverageSpeed?: number | null;
  weekendAllDayAvgSpeedVsSpeedLimit?: number | null;
  weekendAllDayEightyFifthSpeedVsSpeedLimit?: number | null;
  weekendAllDayExtremeViolations?: number | null;
  weekendAllDayFlow?: number | null;
  weekendAllDayMaxSpeed?: number | null;
  weekendAllDayMinSpeed?: number | null;
  weekendAllDayPercentExtremeViolations?: number | null;
  weekendAllDayPercentObserved?: number | null;
  weekendAllDayPercentViolations?: number | null;
  weekendAllDayVariability?: number | null;
  weekendAllDayViolations?: number | null;
  weekendAmPeakAverageEightyFifthSpeed?: number | null;
  weekendAmPeakAverageSpeed?: number | null;
  weekendAmPeakAvgSpeedVsSpeedLimit?: number | null;
  weekendAmPeakEightyFifthSpeedVsSpeedLimit?: number | null;
  weekendAmPeakExtremeViolations?: number | null;
  weekendAmPeakFlow?: number | null;
  weekendAmPeakMaxSpeed?: number | null;
  weekendAmPeakMinSpeed?: number | null;
  weekendAmPeakPercentExtremeViolations?: number | null;
  weekendAmPeakPercentObserved?: number | null;
  weekendAmPeakPercentViolations?: number | null;
  weekendAmPeakVariability?: number | null;
  weekendAmPeakViolations?: number | null;
  weekendEarlyMorningAverageEightyFifthSpeed?: number | null;
  weekendEarlyMorningAverageSpeed?: number | null;
  weekendEarlyMorningAvgSpeedVsSpeedLimit?: number | null;
  weekendEarlyMorningEightyFifthSpeedVsSpeedLimit?: number | null;
  weekendEarlyMorningExtremeViolations?: number | null;
  weekendEarlyMorningFlow?: number | null;
  weekendEarlyMorningMaxSpeed?: number | null;
  weekendEarlyMorningMinSpeed?: number | null;
  weekendEarlyMorningPercentExtremeViolations?: number | null;
  weekendEarlyMorningPercentObserved?: number | null;
  weekendEarlyMorningPercentViolations?: number | null;
  weekendEarlyMorningVariability?: number | null;
  weekendEarlyMorningViolations?: number | null;
  weekendEveningAverageEightyFifthSpeed?: number | null;
  weekendEveningAverageSpeed?: number | null;
  weekendEveningAvgSpeedVsSpeedLimit?: number | null;
  weekendEveningEightyFifthSpeedVsSpeedLimit?: number | null;
  weekendEveningExtremeViolations?: number | null;
  weekendEveningFlow?: number | null;
  weekendEveningMaxSpeed?: number | null;
  weekendEveningMinSpeed?: number | null;
  weekendEveningPercentExtremeViolations?: number | null;
  weekendEveningPercentObserved?: number | null;
  weekendEveningPercentViolations?: number | null;
  weekendEveningVariability?: number | null;
  weekendEveningViolations?: number | null;
  weekendMidDayAverageEightyFifthSpeed?: number | null;
  weekendMidDayAverageSpeed?: number | null;
  weekendMidDayAvgSpeedVsSpeedLimit?: number | null;
  weekendMidDayEightyFifthSpeedVsSpeedLimit?: number | null;
  weekendMidDayExtremeViolations?: number | null;
  weekendMidDayFlow?: number | null;
  weekendMidDayMaxSpeed?: number | null;
  weekendMidDayMinSpeed?: number | null;
  weekendMidDayPercentExtremeViolations?: number | null;
  weekendMidDayPercentObserved?: number | null;
  weekendMidDayPercentViolations?: number | null;
  weekendMidDayVariability?: number | null;
  weekendMidDayViolations?: number | null;
  weekendOffPeakAverageEightyFifthSpeed?: number | null;
  weekendOffPeakAverageSpeed?: number | null;
  weekendOffPeakAvgSpeedVsSpeedLimit?: number | null;
  weekendOffPeakEightyFifthSpeedVsSpeedLimit?: number | null;
  weekendOffPeakExtremeViolations?: number | null;
  weekendOffPeakFlow?: number | null;
  weekendOffPeakMaxSpeed?: number | null;
  weekendOffPeakMinSpeed?: number | null;
  weekendOffPeakPercentExtremeViolations?: number | null;
  weekendOffPeakPercentObserved?: number | null;
  weekendOffPeakPercentViolations?: number | null;
  weekendOffPeakVariability?: number | null;
  weekendOffPeakViolations?: number | null;
  weekendPmPeakAverageEightyFifthSpeed?: number | null;
  weekendPmPeakAverageSpeed?: number | null;
  weekendPmPeakAvgSpeedVsSpeedLimit?: number | null;
  weekendPmPeakEightyFifthSpeedVsSpeedLimit?: number | null;
  weekendPmPeakExtremeViolations?: number | null;
  weekendPmPeakFlow?: number | null;
  weekendPmPeakMaxSpeed?: number | null;
  weekendPmPeakMinSpeed?: number | null;
  weekendPmPeakPercentExtremeViolations?: number | null;
  weekendPmPeakPercentObserved?: number | null;
  weekendPmPeakPercentViolations?: number | null;
  weekendPmPeakVariability?: number | null;
  weekendPmPeakViolations?: number | null;
}

export type MonthAggClassification = typeof MonthAggClassification[keyof typeof MonthAggClassification];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MonthAggClassification = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export interface MonthlyAggregationOptions {
  aggClassification?: MonthAggClassification;
  category?: SpeedCategoryFilter;
  city?: string | null;
  county?: string | null;
  endTime?: string | null;
  limit?: number | null;
  order?: string | null;
  region?: string | null;
  sourceId?: number | null;
  startTime?: string | null;
  timePeriod?: TimePeriodFilter;
}

export interface Int64DataPoint {
  timestamp?: string;
  value?: number;
}

export interface ImpactType {
  description?: string | null;
  id?: string | null;
  name?: string | null;
}

export interface Impact {
  createdBy?: string | null;
  createdOn?: string | null;
  deletedBy?: string | null;
  deletedOn?: string | null;
  description?: string | null;
  end?: string | null;
  endMile?: number;
  id?: string | null;
  impactTypeIds?: string[] | null;
  impactTypes?: ImpactType[] | null;
  segmentIds?: string[] | null;
  start?: string;
  startMile?: number;
  updatedBy?: string | null;
  updatedOn?: string | null;
}

export interface HourlySpeed {
  average?: number;
  binStartTime?: string;
  date?: string;
  eightyFifthSpeed?: number | null;
  extremeViolation?: number | null;
  fifteenthSpeed?: number | null;
  flow?: number | null;
  maxSpeed?: number | null;
  minSpeed?: number | null;
  ninetyFifthSpeed?: number | null;
  ninetyNinthSpeed?: number | null;
  percentObserved?: number | null;
  segmentId?: string;
  sourceDataAnalyzed?: boolean | null;
  sourceId?: number;
  violation?: number | null;
}

export interface GeometryOverlay { [key: string]: any }

export interface GeometryFactory {
  coordinateSequenceFactory?: CoordinateSequenceFactory;
  geometryServices?: NtsGeometryServices;
  precisionModel?: PrecisionModel;
  readonly srid?: number;
}

export type GeometryUserData = unknown | null;

export interface Envelope {
  readonly area?: number;
  centre?: Coordinate;
  readonly diameter?: number;
  readonly height?: number;
  readonly isNull?: boolean;
  readonly maxExtent?: number;
  readonly maxX?: number;
  readonly maxY?: number;
  readonly minExtent?: number;
  readonly minX?: number;
  readonly minY?: number;
  readonly width?: number;
}

export interface Geometry {
  readonly area?: number;
  boundary?: Geometry;
  boundaryDimension?: Dimension;
  centroid?: Point;
  coordinate?: Coordinate;
  readonly coordinates?: readonly Coordinate[] | null;
  dimension?: Dimension;
  envelope?: Geometry;
  envelopeInternal?: Envelope;
  factory?: GeometryFactory;
  readonly geometryType?: string | null;
  interiorPoint?: Point;
  readonly isEmpty?: boolean;
  readonly isRectangle?: boolean;
  readonly isSimple?: boolean;
  readonly isValid?: boolean;
  readonly length?: number;
  readonly numGeometries?: number;
  readonly numPoints?: number;
  ogcGeometryType?: OgcGeometryType;
  pointOnSurface?: Point;
  precisionModel?: PrecisionModel;
  srid?: number;
  userData?: GeometryUserData;
}

export interface Point {
  readonly area?: number;
  boundary?: Geometry;
  boundaryDimension?: Dimension;
  centroid?: Point;
  coordinate?: Coordinate;
  readonly coordinates?: readonly Coordinate[] | null;
  coordinateSequence?: CoordinateSequence;
  dimension?: Dimension;
  envelope?: Geometry;
  envelopeInternal?: Envelope;
  factory?: GeometryFactory;
  readonly geometryType?: string | null;
  interiorPoint?: Point;
  readonly isEmpty?: boolean;
  readonly isRectangle?: boolean;
  readonly isSimple?: boolean;
  readonly isValid?: boolean;
  readonly length?: number;
  m?: number;
  readonly numGeometries?: number;
  readonly numPoints?: number;
  ogcGeometryType?: OgcGeometryType;
  pointOnSurface?: Point;
  precisionModel?: PrecisionModel;
  srid?: number;
  userData?: PointUserData;
  x?: number;
  y?: number;
  z?: number;
}

export interface EffectivenessOfStrategiesOptions {
  endTime?: string | null;
  segmentIds?: string[] | null;
  startTime?: string | null;
  strategyImplementedDate?: string;
}

export interface EffectivenessOfStrategiesDto {
  after?: TimeSegmentEffectiveness;
  before?: TimeSegmentEffectiveness;
  changeInAverageSpeed?: number;
  changeInEightyFifthPercentileSpeed?: number;
  changeInPercentExtremeViolations?: number;
  changeInPercentViolations?: number;
  changeInVariability?: number;
  segmentId?: string;
  segmentName?: string | null;
  speedLimit?: number;
  weeklyEffectiveness?: TimeSegmentEffectiveness[] | null;
}

export interface DoubleDataPoint {
  timestamp?: string;
  value?: number;
}

export type Dimension = typeof Dimension[keyof typeof Dimension];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Dimension = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_MINUS_3: -3,
  NUMBER_MINUS_2: -2,
  NUMBER_MINUS_1: -1,
} as const;

export type DayOfWeek = typeof DayOfWeek[keyof typeof DayOfWeek];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DayOfWeek = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
} as const;

export interface DataQualitySegment {
  dataPoints?: DoubleDataPoint[] | null;
  endingMilePoint?: number;
  segmentId?: string;
  segmentName?: string | null;
  startingMilePoint?: number;
}

export interface DataQualitySource {
  endDate?: string;
  name?: string | null;
  segments?: DataQualitySegment[] | null;
  sourceId?: number;
  startDate?: string;
}

export interface DataQualityOptions {
  endDate?: string;
  segmentIds?: string[] | null;
  startDate?: string;
}

export interface DailySpeedViolationsDto {
  dailyExtremeViolationsCount?: number;
  dailyFlow?: number;
  dailyPercentExtremeViolations?: number;
  dailyPercentViolations?: number;
  dailyViolationsCount?: number;
  date?: string;
}

export interface CoordinateSequenceFactory {
  ordinates?: Ordinates;
}

export interface CoordinateSequence {
  readonly count?: number;
  readonly dimension?: number;
  first?: Coordinate;
  readonly hasM?: boolean;
  readonly hasZ?: boolean;
  last?: Coordinate;
  readonly measures?: number;
  readonly mOrdinateIndex?: number;
  ordinates?: Ordinates;
  readonly spatial?: number;
  readonly zOrdinateIndex?: number;
}

export interface CoordinateEqualityComparer { [key: string]: any }

export interface Coordinate {
  coordinateValue?: Coordinate;
  readonly isValid?: boolean;
  m?: number;
  x?: number;
  y?: number;
  z?: number;
}

export interface CongestionTrackingOptions {
  endDate?: string;
  segmentId?: string | null;
  sourceId?: number;
  startDate?: string;
}

export interface CongestionTrackingDto {
  data?: SpeedDataDto[] | null;
  endDate?: string;
  endingMilePoint?: number;
  segmentId?: string;
  segmentName?: string | null;
  speedLimit?: number;
  startDate?: string;
  startingMilePoint?: number;
}

export interface AverageAndEightyFifthSeriesData {
  average?: DoubleDataPoint[] | null;
  eightyFifth?: Int64DataPoint[] | null;
}

