version: '3.8'

services:
  webui:
    build:
      context: ./WebUI
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - configapi
      - dataapi
      - signalcontroller
      - watchdog
      - reportapi
      - identityapi

  configapi:
    build:
      dockerfile: ./ConfigApi/Dockerfile
    ports:
      - "44313:44313"

  dataapi:
    build:
      dockerfile: ./DataApi/Dockerfile
    ports:
      - "8082:80"

  signalcontroller:
    build:
      dockerfile: ./SignalControllerLogger/Dockerfile
    ports:
      - "8083:80"

  watchdog:
    build:
      dockerfile: ./WatchDog/Dockerfile
    ports:
      - "8084:80"

  reportapi:
    build:
      dockerfile: ./ReportApi/Dockerfile
    ports:
      - "8085:80"

  identityapi:
    build:
      dockerfile: ./Identity/Dockerfile
    ports:
      - "8086:80"

networks:
  default:
    driver: bridge
