version: '3.8'

x-environment: &default-environment
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_Kestrel__Certificates__Default__Password: password
  ASPNETCORE_Kestrel__Certificates__Default__Path: /root/.aspnet/https/aspnetapp.pfx
  ConnectionStrings__ConfigContext__Provider: "PostgreSQL"
  ConnectionStrings__AggregationContext__Provider: "PostgreSQL"
  ConnectionStrings__EventLogContext__Provider: "PostgreSQL"
  ConnectionStrings__IdentityContext__Provider: "PostgreSQL"
  Jwt__ExpireDays: "1"
  Jwt__Key: "ATSPMProductionIdentityOpenSource2024"
  Jwt__Issuer: "AvenueConsultants"

services:
  webui:
    build:
      context: ./WebUI
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - configapi
      - dataapi
      - signalcontroller
      - watchdog
      - reportapi
      - identityapi

  configapi:
    build:
      dockerfile: ./ConfigApi/Dockerfile
    ports:
      - "44313:44313"
    environment:
      <<: *default-environment
      ASPNETCORE_URLS: https://+:44313
    volumes:
      - ./certs:/root/.aspnet/https:ro
    user: root

  dataapi:
    build:
      dockerfile: ./DataApi/Dockerfile
    ports:
      - "8082:80"

  signalcontroller:
    build:
      dockerfile: ./SignalControllerLogger/Dockerfile
    ports:
      - "8083:80"

  watchdog:
    build:
      dockerfile: ./WatchDog/Dockerfile
    ports:
      - "8084:80"

  reportapi:
    build:
      dockerfile: ./ReportApi/Dockerfile
    ports:
      - "8085:80"

  identityapi:
    build:
      dockerfile: ./Identity/Dockerfile
    ports:
      - "8086:80"

networks:
  default:
    driver: bridge
