version: '3.8'

services:
#   Locationcontrollerlogger:
#     image: ${DOCKER_REGISTRY-}Locationcontrollerlogger
#     network_mode: "host"
#     build:
#       context: .
#       dockerfile: LocationControllerLogger/Dockerfile
#     tty: true

 report_api:    
    build:
      context: .   # This sets the context to the ProjectRoot
      dockerfile: ReportApi/Dockerfile
    image: reportapi:v1
    ports:
      - "8080:80"