version: '3.4'

services:
  signalcontrollerlogger:
    image: ${DOCKER_REGISTRY-}signalcontrollerlogger
    network_mode: "host"
    build:
      context: .
      dockerfile: SignalControllerLogger/Dockerfile
    tty: true
  ATSPM.Application.Reports:
    image: ${DOCKER_REGISTRY-}reports
    build:
      context: .
      dockerfile: Reports/Dockerfile
    ports:
      - "8080:80"

 