version: '3.8'

services:
  webui:
    build:
      context: ./WebUI
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - configapi
      - dataapi
      - signalcontroller
      - watchdog
      - reportapi
      - identityapi

  configapi:
    build:
      context: ./ConfigApi
      dockerfile: Dockerfile
    ports:
      - "8081:80"

  dataapi:
    build:
      context: ./DataApi
      dockerfile: Dockerfile
    ports:
      - "8082:80"

  signalcontroller:
    build:
      context: ./SignalControllerLogger
      dockerfile: Dockerfile
    ports:
      - "8083:80"

  watchdog:
    build:
      context: ./WatchDog
      dockerfile: Dockerfile
    ports:
      - "8084:80"

  reportapi:
    build:
      context: ./ReportApi
      dockerfile: Dockerfile
    ports:
      - "8085:80"

  identityapi:
    build:
      context: ./Identity
      dockerfile: Dockerfile
    ports:
      - "8086:80"

networks:
  default:
    driver: bridge
