/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * ATSPM Report Api
 * ATSPM Reporting with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  AggregationOptions,
  AggregationResult,
  ProblemDetails
} from '../report-api.schemas';

import { reportsRequest } from '../../../lib/axios';




export type getAggregationTestDataResponse200 = {
  data: AggregationResult[]
  status: 200
}

export type getAggregationTestDataResponse406 = {
  data: ProblemDetails
  status: 406
}

export type getAggregationTestDataResponseSuccess = (getAggregationTestDataResponse200) & {
  headers: Headers;
};
export type getAggregationTestDataResponseError = (getAggregationTestDataResponse406) & {
  headers: Headers;
};

export type getAggregationTestDataResponse = (getAggregationTestDataResponseSuccess | getAggregationTestDataResponseError)

export const getGetAggregationTestDataUrl = () => {




  return `/api/v1/Aggregation/test`
}

/**
 * @summary Get example data for testing
 */
export const getAggregationTestData = async ( options?: RequestInit): Promise<getAggregationTestDataResponse> => {

  return reportsRequest<getAggregationTestDataResponse>(getGetAggregationTestDataUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAggregationTestDataQueryKey = () => {
    return [
    `/api/v1/Aggregation/test`
    ] as const;
    }


export const getGetAggregationTestDataQueryOptions = <TData = Awaited<ReturnType<typeof getAggregationTestData>>, TError = ProblemDetails>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAggregationTestData>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAggregationTestDataQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAggregationTestData>>> = ({ signal }) => getAggregationTestData({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAggregationTestData>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAggregationTestDataQueryResult = NonNullable<Awaited<ReturnType<typeof getAggregationTestData>>>
export type GetAggregationTestDataQueryError = ProblemDetails


/**
 * @summary Get example data for testing
 */

export function useGetAggregationTestData<TData = Awaited<ReturnType<typeof getAggregationTestData>>, TError = ProblemDetails>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAggregationTestData>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAggregationTestDataQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getAggregationReportDataResponse200 = {
  data: AggregationResult[]
  status: 200
}

export type getAggregationReportDataResponse400 = {
  data: ProblemDetails
  status: 400
}

export type getAggregationReportDataResponse406 = {
  data: ProblemDetails
  status: 406
}

export type getAggregationReportDataResponseSuccess = (getAggregationReportDataResponse200) & {
  headers: Headers;
};
export type getAggregationReportDataResponseError = (getAggregationReportDataResponse400 | getAggregationReportDataResponse406) & {
  headers: Headers;
};

export type getAggregationReportDataResponse = (getAggregationReportDataResponseSuccess | getAggregationReportDataResponseError)

export const getGetAggregationReportDataUrl = () => {




  return `/api/v1/Aggregation/getReportData`
}

/**
 * @summary Get report data
 */
export const getAggregationReportData = async (aggregationOptions?: AggregationOptions, options?: RequestInit): Promise<getAggregationReportDataResponse> => {

  return reportsRequest<getAggregationReportDataResponse>(getGetAggregationReportDataUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      aggregationOptions,)
  }
);}




export const getGetAggregationReportDataMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getAggregationReportData>>, TError,{data?: AggregationOptions}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getAggregationReportData>>, TError,{data?: AggregationOptions}, TContext> => {

const mutationKey = ['getAggregationReportData'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getAggregationReportData>>, {data?: AggregationOptions}> = (props) => {
          const {data} = props ?? {};

          return  getAggregationReportData(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetAggregationReportDataMutationResult = NonNullable<Awaited<ReturnType<typeof getAggregationReportData>>>
    export type GetAggregationReportDataMutationBody = AggregationOptions | undefined
    export type GetAggregationReportDataMutationError = ProblemDetails

    /**
 * @summary Get report data
 */
export const useGetAggregationReportData = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getAggregationReportData>>, TError,{data?: AggregationOptions}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof getAggregationReportData>>,
        TError,
        {data?: AggregationOptions},
        TContext
      > => {
      return useMutation(getGetAggregationReportDataMutationOptions(options));
    }
