/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * ATSPM Report Api
 * ATSPM Reporting with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  ArrivalOnRedOptions,
  ArrivalOnRedResult,
  ProblemDetails
} from '../report-api.schemas';

import { reportsRequest } from '../../../lib/axios';




export type getArrivalOnRedTestDataResponse200 = {
  data: ArrivalOnRedResult[]
  status: 200
}

export type getArrivalOnRedTestDataResponse406 = {
  data: ProblemDetails
  status: 406
}

export type getArrivalOnRedTestDataResponseSuccess = (getArrivalOnRedTestDataResponse200) & {
  headers: Headers;
};
export type getArrivalOnRedTestDataResponseError = (getArrivalOnRedTestDataResponse406) & {
  headers: Headers;
};

export type getArrivalOnRedTestDataResponse = (getArrivalOnRedTestDataResponseSuccess | getArrivalOnRedTestDataResponseError)

export const getGetArrivalOnRedTestDataUrl = () => {




  return `/api/v1/ArrivalOnRed/test`
}

/**
 * @summary Get example data for testing
 */
export const getArrivalOnRedTestData = async ( options?: RequestInit): Promise<getArrivalOnRedTestDataResponse> => {

  return reportsRequest<getArrivalOnRedTestDataResponse>(getGetArrivalOnRedTestDataUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetArrivalOnRedTestDataQueryKey = () => {
    return [
    `/api/v1/ArrivalOnRed/test`
    ] as const;
    }


export const getGetArrivalOnRedTestDataQueryOptions = <TData = Awaited<ReturnType<typeof getArrivalOnRedTestData>>, TError = ProblemDetails>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getArrivalOnRedTestData>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetArrivalOnRedTestDataQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getArrivalOnRedTestData>>> = ({ signal }) => getArrivalOnRedTestData({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getArrivalOnRedTestData>>, TError, TData> & { queryKey: QueryKey }
}

export type GetArrivalOnRedTestDataQueryResult = NonNullable<Awaited<ReturnType<typeof getArrivalOnRedTestData>>>
export type GetArrivalOnRedTestDataQueryError = ProblemDetails


/**
 * @summary Get example data for testing
 */

export function useGetArrivalOnRedTestData<TData = Awaited<ReturnType<typeof getArrivalOnRedTestData>>, TError = ProblemDetails>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getArrivalOnRedTestData>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetArrivalOnRedTestDataQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getArrivalOnRedReportDataResponse200 = {
  data: ArrivalOnRedResult[]
  status: 200
}

export type getArrivalOnRedReportDataResponse400 = {
  data: ProblemDetails
  status: 400
}

export type getArrivalOnRedReportDataResponse406 = {
  data: ProblemDetails
  status: 406
}

export type getArrivalOnRedReportDataResponseSuccess = (getArrivalOnRedReportDataResponse200) & {
  headers: Headers;
};
export type getArrivalOnRedReportDataResponseError = (getArrivalOnRedReportDataResponse400 | getArrivalOnRedReportDataResponse406) & {
  headers: Headers;
};

export type getArrivalOnRedReportDataResponse = (getArrivalOnRedReportDataResponseSuccess | getArrivalOnRedReportDataResponseError)

export const getGetArrivalOnRedReportDataUrl = () => {




  return `/api/v1/ArrivalOnRed/getReportData`
}

/**
 * @summary Get report data
 */
export const getArrivalOnRedReportData = async (arrivalOnRedOptions?: ArrivalOnRedOptions, options?: RequestInit): Promise<getArrivalOnRedReportDataResponse> => {

  return reportsRequest<getArrivalOnRedReportDataResponse>(getGetArrivalOnRedReportDataUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      arrivalOnRedOptions,)
  }
);}




export const getGetArrivalOnRedReportDataMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getArrivalOnRedReportData>>, TError,{data?: ArrivalOnRedOptions}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getArrivalOnRedReportData>>, TError,{data?: ArrivalOnRedOptions}, TContext> => {

const mutationKey = ['getArrivalOnRedReportData'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getArrivalOnRedReportData>>, {data?: ArrivalOnRedOptions}> = (props) => {
          const {data} = props ?? {};

          return  getArrivalOnRedReportData(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetArrivalOnRedReportDataMutationResult = NonNullable<Awaited<ReturnType<typeof getArrivalOnRedReportData>>>
    export type GetArrivalOnRedReportDataMutationBody = ArrivalOnRedOptions | undefined
    export type GetArrivalOnRedReportDataMutationError = ProblemDetails

    /**
 * @summary Get report data
 */
export const useGetArrivalOnRedReportData = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getArrivalOnRedReportData>>, TError,{data?: ArrivalOnRedOptions}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof getArrivalOnRedReportData>>,
        TError,
        {data?: ArrivalOnRedOptions},
        TContext
      > => {
      return useMutation(getGetArrivalOnRedReportDataMutationOptions(options));
    }
