/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * ATSPM Report Data Api
 * ATSPM Report Data with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  LinkPivotOptions,
  LinkPivotPcdOptions,
  LinkPivotPcdResult,
  LinkPivotResult,
  ProblemDetails
} from '../aTSPMReportDataApi.schemas';

import { reportsRequest } from '../../../lib/axios';




export const getLinkPivotPcdData = (
    linkPivotPcdOptions: LinkPivotPcdOptions,
 signal?: AbortSignal
) => {
      
      
      return reportsRequest<LinkPivotPcdResult>(
      {url: `/api/v1/LinkPivot/getPcdData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linkPivotPcdOptions, signal
    },
      );
    }
  


export const getGetLinkPivotPcdDataMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLinkPivotPcdData>>, TError,{data: LinkPivotPcdOptions}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getLinkPivotPcdData>>, TError,{data: LinkPivotPcdOptions}, TContext> => {

const mutationKey = ['getLinkPivotPcdData'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getLinkPivotPcdData>>, {data: LinkPivotPcdOptions}> = (props) => {
          const {data} = props ?? {};

          return  getLinkPivotPcdData(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetLinkPivotPcdDataMutationResult = NonNullable<Awaited<ReturnType<typeof getLinkPivotPcdData>>>
    export type GetLinkPivotPcdDataMutationBody = LinkPivotPcdOptions
    export type GetLinkPivotPcdDataMutationError = ProblemDetails

    export const useGetLinkPivotPcdData = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLinkPivotPcdData>>, TError,{data: LinkPivotPcdOptions}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof getLinkPivotPcdData>>,
        TError,
        {data: LinkPivotPcdOptions},
        TContext
      > => {

      const mutationOptions = getGetLinkPivotPcdDataMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * @summary Get example data for testing
 */
export const getLinkPivotTestData = (
    
 signal?: AbortSignal
) => {
      
      
      return reportsRequest<LinkPivotResult>(
      {url: `/api/v1/LinkPivot/test`, method: 'GET', signal
    },
      );
    }
  

export const getGetLinkPivotTestDataQueryKey = () => {
    return [`/api/v1/LinkPivot/test`] as const;
    }

    
export const getGetLinkPivotTestDataQueryOptions = <TData = Awaited<ReturnType<typeof getLinkPivotTestData>>, TError = ProblemDetails>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLinkPivotTestData>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLinkPivotTestDataQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLinkPivotTestData>>> = ({ signal }) => getLinkPivotTestData(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLinkPivotTestData>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLinkPivotTestDataQueryResult = NonNullable<Awaited<ReturnType<typeof getLinkPivotTestData>>>
export type GetLinkPivotTestDataQueryError = ProblemDetails


/**
 * @summary Get example data for testing
 */

export function useGetLinkPivotTestData<TData = Awaited<ReturnType<typeof getLinkPivotTestData>>, TError = ProblemDetails>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLinkPivotTestData>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetLinkPivotTestDataQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get report data
 */
export const getLinkPivotReportData = (
    linkPivotOptions: LinkPivotOptions,
 signal?: AbortSignal
) => {
      
      
      return reportsRequest<LinkPivotResult>(
      {url: `/api/v1/LinkPivot/getReportData`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linkPivotOptions, signal
    },
      );
    }
  


export const getGetLinkPivotReportDataMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLinkPivotReportData>>, TError,{data: LinkPivotOptions}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getLinkPivotReportData>>, TError,{data: LinkPivotOptions}, TContext> => {

const mutationKey = ['getLinkPivotReportData'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getLinkPivotReportData>>, {data: LinkPivotOptions}> = (props) => {
          const {data} = props ?? {};

          return  getLinkPivotReportData(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetLinkPivotReportDataMutationResult = NonNullable<Awaited<ReturnType<typeof getLinkPivotReportData>>>
    export type GetLinkPivotReportDataMutationBody = LinkPivotOptions
    export type GetLinkPivotReportDataMutationError = ProblemDetails

    /**
 * @summary Get report data
 */
export const useGetLinkPivotReportData = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLinkPivotReportData>>, TError,{data: LinkPivotOptions}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof getLinkPivotReportData>>,
        TError,
        {data: LinkPivotOptions},
        TContext
      > => {

      const mutationOptions = getGetLinkPivotReportDataMutationOptions(options);

      return useMutation(mutationOptions );
    }
    