/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * ATSPM Report Api
 * ATSPM Reporting with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  GapDurationOptions,
  GapDurationResult,
  ProblemDetails
} from '../report-api.schemas';

import { reportsRequest } from '../../../lib/axios';




export type getLeftTurnGapDurationTestDataResponse200 = {
  data: GapDurationResult
  status: 200
}

export type getLeftTurnGapDurationTestDataResponse406 = {
  data: ProblemDetails
  status: 406
}

export type getLeftTurnGapDurationTestDataResponseSuccess = (getLeftTurnGapDurationTestDataResponse200) & {
  headers: Headers;
};
export type getLeftTurnGapDurationTestDataResponseError = (getLeftTurnGapDurationTestDataResponse406) & {
  headers: Headers;
};

export type getLeftTurnGapDurationTestDataResponse = (getLeftTurnGapDurationTestDataResponseSuccess | getLeftTurnGapDurationTestDataResponseError)

export const getGetLeftTurnGapDurationTestDataUrl = () => {




  return `/api/v1/LeftTurnGapDuration/test`
}

/**
 * @summary Get example data for testing
 */
export const getLeftTurnGapDurationTestData = async ( options?: RequestInit): Promise<getLeftTurnGapDurationTestDataResponse> => {

  return reportsRequest<getLeftTurnGapDurationTestDataResponse>(getGetLeftTurnGapDurationTestDataUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLeftTurnGapDurationTestDataQueryKey = () => {
    return [
    `/api/v1/LeftTurnGapDuration/test`
    ] as const;
    }


export const getGetLeftTurnGapDurationTestDataQueryOptions = <TData = Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError = ProblemDetails>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLeftTurnGapDurationTestDataQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>> = ({ signal }) => getLeftTurnGapDurationTestData({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError, TData> & { queryKey: QueryKey }
}

export type GetLeftTurnGapDurationTestDataQueryResult = NonNullable<Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>>
export type GetLeftTurnGapDurationTestDataQueryError = ProblemDetails


/**
 * @summary Get example data for testing
 */

export function useGetLeftTurnGapDurationTestData<TData = Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError = ProblemDetails>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getLeftTurnGapDurationTestData>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetLeftTurnGapDurationTestDataQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getLeftTurnGapDurationReportDataResponse200 = {
  data: GapDurationResult
  status: 200
}

export type getLeftTurnGapDurationReportDataResponse400 = {
  data: ProblemDetails
  status: 400
}

export type getLeftTurnGapDurationReportDataResponse406 = {
  data: ProblemDetails
  status: 406
}

export type getLeftTurnGapDurationReportDataResponseSuccess = (getLeftTurnGapDurationReportDataResponse200) & {
  headers: Headers;
};
export type getLeftTurnGapDurationReportDataResponseError = (getLeftTurnGapDurationReportDataResponse400 | getLeftTurnGapDurationReportDataResponse406) & {
  headers: Headers;
};

export type getLeftTurnGapDurationReportDataResponse = (getLeftTurnGapDurationReportDataResponseSuccess | getLeftTurnGapDurationReportDataResponseError)

export const getGetLeftTurnGapDurationReportDataUrl = () => {




  return `/api/v1/LeftTurnGapDuration/getReportData`
}

/**
 * @summary Get report data
 */
export const getLeftTurnGapDurationReportData = async (gapDurationOptions?: GapDurationOptions, options?: RequestInit): Promise<getLeftTurnGapDurationReportDataResponse> => {

  return reportsRequest<getLeftTurnGapDurationReportDataResponse>(getGetLeftTurnGapDurationReportDataUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      gapDurationOptions,)
  }
);}




export const getGetLeftTurnGapDurationReportDataMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLeftTurnGapDurationReportData>>, TError,{data?: GapDurationOptions}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getLeftTurnGapDurationReportData>>, TError,{data?: GapDurationOptions}, TContext> => {

const mutationKey = ['getLeftTurnGapDurationReportData'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getLeftTurnGapDurationReportData>>, {data?: GapDurationOptions}> = (props) => {
          const {data} = props ?? {};

          return  getLeftTurnGapDurationReportData(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetLeftTurnGapDurationReportDataMutationResult = NonNullable<Awaited<ReturnType<typeof getLeftTurnGapDurationReportData>>>
    export type GetLeftTurnGapDurationReportDataMutationBody = GapDurationOptions | undefined
    export type GetLeftTurnGapDurationReportDataMutationError = ProblemDetails

    /**
 * @summary Get report data
 */
export const useGetLeftTurnGapDurationReportData = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLeftTurnGapDurationReportData>>, TError,{data?: GapDurationOptions}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof getLeftTurnGapDurationReportData>>,
        TError,
        {data?: GapDurationOptions},
        TContext
      > => {
      return useMutation(getGetLeftTurnGapDurationReportDataMutationOptions(options));
    }
