// #region license
// Copyright 2026 Utah Departement of Transportation
// for WebUI - logging.msw.ts
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// #endregion

/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * Atspm Data Api
 * Download Atspm Event Logs and Aggregations
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  DeviceEventDownload
} from '../data-api.schemas';


export const getGetLoggingSyncDeviceEventsResponseMock = (): DeviceEventDownload[] => (faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({deviceId: faker.helpers.arrayElement([faker.number.int(), undefined]), ipaddress: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), deviceType: faker.helpers.arrayElement([faker.helpers.arrayElement([0,1,2,3,4,5,6] as const), undefined]), beforeWorkflowEventCount: faker.helpers.arrayElement([faker.number.int(), undefined]), afterWorkflowEventCount: faker.helpers.arrayElement([faker.number.int(), undefined]), changeInEventCount: faker.helpers.arrayElement([faker.number.int(), undefined])})), Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({deviceId: faker.helpers.arrayElement([faker.number.int(), undefined]), ipaddress: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), deviceType: faker.helpers.arrayElement([faker.helpers.arrayElement([0,1,2,3,4,5,6] as const), undefined]), beforeWorkflowEventCount: faker.helpers.arrayElement([faker.number.int(), undefined]), afterWorkflowEventCount: faker.helpers.arrayElement([faker.number.int(), undefined]), changeInEventCount: faker.helpers.arrayElement([faker.number.int(), undefined])}))]))


export const getGetLoggingSyncDeviceEventsMockHandler = (overrideResponse?: DeviceEventDownload[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DeviceEventDownload[]> | DeviceEventDownload[]), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/Logging/SyncDeviceEvents', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetLoggingSyncDeviceEventsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getLoggingMock = () => [
  getGetLoggingSyncDeviceEventsMockHandler()
]
