/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * ATSPM Report Api
 * ATSPM Reporting with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  ProblemDetails,
  TurningMovementCountsOptions,
  TurningMovementCountsResult
} from '../report-api.schemas';

import { reportsRequest } from '../../../lib/axios';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;





export type getTurningMovementCountsTestDataResponse200 = {
  data: TurningMovementCountsResult
  status: 200
}

export type getTurningMovementCountsTestDataResponse406 = {
  data: ProblemDetails
  status: 406
}

export type getTurningMovementCountsTestDataResponseSuccess = (getTurningMovementCountsTestDataResponse200) & {
  headers: Headers;
};
export type getTurningMovementCountsTestDataResponseError = (getTurningMovementCountsTestDataResponse406) & {
  headers: Headers;
};

export type getTurningMovementCountsTestDataResponse = (getTurningMovementCountsTestDataResponseSuccess | getTurningMovementCountsTestDataResponseError)

export const getGetTurningMovementCountsTestDataUrl = () => {




  return `/api/v1/TurningMovementCounts/test`
}

/**
 * @summary Get example data for testing
 */
export const getTurningMovementCountsTestData = async ( options?: RequestInit): Promise<getTurningMovementCountsTestDataResponse> => {

  return reportsRequest<getTurningMovementCountsTestDataResponse>(getGetTurningMovementCountsTestDataUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTurningMovementCountsTestDataQueryKey = () => {
    return [
    `/api/v1/TurningMovementCounts/test`
    ] as const;
    }


export const getGetTurningMovementCountsTestDataQueryOptions = <TData = Awaited<ReturnType<typeof getTurningMovementCountsTestData>>, TError = ProblemDetails>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTurningMovementCountsTestData>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTurningMovementCountsTestDataQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTurningMovementCountsTestData>>> = ({ signal }) => getTurningMovementCountsTestData({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTurningMovementCountsTestData>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTurningMovementCountsTestDataQueryResult = NonNullable<Awaited<ReturnType<typeof getTurningMovementCountsTestData>>>
export type GetTurningMovementCountsTestDataQueryError = ProblemDetails


/**
 * @summary Get example data for testing
 */

export function useGetTurningMovementCountsTestData<TData = Awaited<ReturnType<typeof getTurningMovementCountsTestData>>, TError = ProblemDetails>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTurningMovementCountsTestData>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTurningMovementCountsTestDataQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getTurningMovementCountsReportDataResponse200 = {
  data: TurningMovementCountsResult
  status: 200
}

export type getTurningMovementCountsReportDataResponse400 = {
  data: ProblemDetails
  status: 400
}

export type getTurningMovementCountsReportDataResponse406 = {
  data: ProblemDetails
  status: 406
}

export type getTurningMovementCountsReportDataResponseSuccess = (getTurningMovementCountsReportDataResponse200) & {
  headers: Headers;
};
export type getTurningMovementCountsReportDataResponseError = (getTurningMovementCountsReportDataResponse400 | getTurningMovementCountsReportDataResponse406) & {
  headers: Headers;
};

export type getTurningMovementCountsReportDataResponse = (getTurningMovementCountsReportDataResponseSuccess | getTurningMovementCountsReportDataResponseError)

export const getGetTurningMovementCountsReportDataUrl = () => {




  return `/api/v1/TurningMovementCounts/getReportData`
}

/**
 * @summary Get report data
 */
export const getTurningMovementCountsReportData = async (turningMovementCountsOptions?: NonReadonly<TurningMovementCountsOptions>, options?: RequestInit): Promise<getTurningMovementCountsReportDataResponse> => {

  return reportsRequest<getTurningMovementCountsReportDataResponse>(getGetTurningMovementCountsReportDataUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      turningMovementCountsOptions,)
  }
);}




export const getGetTurningMovementCountsReportDataMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getTurningMovementCountsReportData>>, TError,{data?: NonReadonly<TurningMovementCountsOptions>}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getTurningMovementCountsReportData>>, TError,{data?: NonReadonly<TurningMovementCountsOptions>}, TContext> => {

const mutationKey = ['getTurningMovementCountsReportData'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getTurningMovementCountsReportData>>, {data?: NonReadonly<TurningMovementCountsOptions>}> = (props) => {
          const {data} = props ?? {};

          return  getTurningMovementCountsReportData(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetTurningMovementCountsReportDataMutationResult = NonNullable<Awaited<ReturnType<typeof getTurningMovementCountsReportData>>>
    export type GetTurningMovementCountsReportDataMutationBody = NonReadonly<TurningMovementCountsOptions> | undefined
    export type GetTurningMovementCountsReportDataMutationError = ProblemDetails

    /**
 * @summary Get report data
 */
export const useGetTurningMovementCountsReportData = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getTurningMovementCountsReportData>>, TError,{data?: NonReadonly<TurningMovementCountsOptions>}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof getTurningMovementCountsReportData>>,
        TError,
        {data?: NonReadonly<TurningMovementCountsOptions>},
        TContext
      > => {
      return useMutation(getGetTurningMovementCountsReportDataMutationOptions(options));
    }
