/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * ATSPM Log Data Api
 * ATSPM Log Data with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from 'react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  GetAggregationArchivedAggregationsFromLocationIdentifierAndDataTypeParams,
  GetAggregationArchivedAggregationsFromLocationIdentifierParams,
  ProblemDetails
} from '../data-api.schemas';

import { dataRequest } from '../../../lib/axios';




/**
 * @summary Returns the possible aggregated data types
 */
export const getAggregationDataTypes = (
    
 signal?: AbortSignal
) => {
      
      
      return dataRequest<string[]>(
      {url: `/api/v1/Aggregation/GetDataTypes`, method: 'GET', signal
    },
      );
    }
  

export const getGetAggregationDataTypesQueryKey = () => {
    return [`/api/v1/Aggregation/GetDataTypes`] as const;
    }

    
export const getGetAggregationDataTypesQueryOptions = <TData = Awaited<ReturnType<typeof getAggregationDataTypes>>, TError = ProblemDetails>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAggregationDataTypes>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAggregationDataTypesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAggregationDataTypes>>> = ({ signal }) => getAggregationDataTypes(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAggregationDataTypes>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAggregationDataTypesQueryResult = NonNullable<Awaited<ReturnType<typeof getAggregationDataTypes>>>
export type GetAggregationDataTypesQueryError = ProblemDetails


/**
 * @summary Returns the possible aggregated data types
 */

export function useGetAggregationDataTypes<TData = Awaited<ReturnType<typeof getAggregationDataTypes>>, TError = ProblemDetails>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAggregationDataTypes>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAggregationDataTypesQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all aggregations for location by date
 */
export const getAggregationArchivedAggregationsFromLocationIdentifier = (
    locationIdentifier: string,
    params?: GetAggregationArchivedAggregationsFromLocationIdentifierParams,
 signal?: AbortSignal
) => {
      
      
      return dataRequest<void>(
      {url: `/api/v1/Aggregation/GetArchivedAggregations/${locationIdentifier}`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetAggregationArchivedAggregationsFromLocationIdentifierQueryKey = (locationIdentifier: string,
    params?: GetAggregationArchivedAggregationsFromLocationIdentifierParams,) => {
    return [`/api/v1/Aggregation/GetArchivedAggregations/${locationIdentifier}`, ...(params ? [params]: [])] as const;
    }

    
export const getGetAggregationArchivedAggregationsFromLocationIdentifierQueryOptions = <TData = Awaited<ReturnType<typeof getAggregationArchivedAggregationsFromLocationIdentifier>>, TError = ProblemDetails>(locationIdentifier: string,
    params?: GetAggregationArchivedAggregationsFromLocationIdentifierParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAggregationArchivedAggregationsFromLocationIdentifier>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAggregationArchivedAggregationsFromLocationIdentifierQueryKey(locationIdentifier,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAggregationArchivedAggregationsFromLocationIdentifier>>> = ({ signal }) => getAggregationArchivedAggregationsFromLocationIdentifier(locationIdentifier,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(locationIdentifier), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAggregationArchivedAggregationsFromLocationIdentifier>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAggregationArchivedAggregationsFromLocationIdentifierQueryResult = NonNullable<Awaited<ReturnType<typeof getAggregationArchivedAggregationsFromLocationIdentifier>>>
export type GetAggregationArchivedAggregationsFromLocationIdentifierQueryError = ProblemDetails


/**
 * @summary Get all aggregations for location by date
 */

export function useGetAggregationArchivedAggregationsFromLocationIdentifier<TData = Awaited<ReturnType<typeof getAggregationArchivedAggregationsFromLocationIdentifier>>, TError = ProblemDetails>(
 locationIdentifier: string,
    params?: GetAggregationArchivedAggregationsFromLocationIdentifierParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAggregationArchivedAggregationsFromLocationIdentifier>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAggregationArchivedAggregationsFromLocationIdentifierQueryOptions(locationIdentifier,params,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get all aggregations for location by date and datatype
 */
export const getAggregationArchivedAggregationsFromLocationIdentifierAndDataType = (
    locationIdentifier: string,
    dataType: string,
    params?: GetAggregationArchivedAggregationsFromLocationIdentifierAndDataTypeParams,
 signal?: AbortSignal
) => {
      
      
      return dataRequest<void>(
      {url: `/api/v1/Aggregation/GetArchivedAggregations/${locationIdentifier}/${dataType}`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetAggregationArchivedAggregationsFromLocationIdentifierAndDataTypeQueryKey = (locationIdentifier: string,
    dataType: string,
    params?: GetAggregationArchivedAggregationsFromLocationIdentifierAndDataTypeParams,) => {
    return [`/api/v1/Aggregation/GetArchivedAggregations/${locationIdentifier}/${dataType}`, ...(params ? [params]: [])] as const;
    }

    
export const getGetAggregationArchivedAggregationsFromLocationIdentifierAndDataTypeQueryOptions = <TData = Awaited<ReturnType<typeof getAggregationArchivedAggregationsFromLocationIdentifierAndDataType>>, TError = ProblemDetails>(locationIdentifier: string,
    dataType: string,
    params?: GetAggregationArchivedAggregationsFromLocationIdentifierAndDataTypeParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAggregationArchivedAggregationsFromLocationIdentifierAndDataType>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAggregationArchivedAggregationsFromLocationIdentifierAndDataTypeQueryKey(locationIdentifier,dataType,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAggregationArchivedAggregationsFromLocationIdentifierAndDataType>>> = ({ signal }) => getAggregationArchivedAggregationsFromLocationIdentifierAndDataType(locationIdentifier,dataType,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(locationIdentifier && dataType), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAggregationArchivedAggregationsFromLocationIdentifierAndDataType>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAggregationArchivedAggregationsFromLocationIdentifierAndDataTypeQueryResult = NonNullable<Awaited<ReturnType<typeof getAggregationArchivedAggregationsFromLocationIdentifierAndDataType>>>
export type GetAggregationArchivedAggregationsFromLocationIdentifierAndDataTypeQueryError = ProblemDetails


/**
 * @summary Get all aggregations for location by date and datatype
 */

export function useGetAggregationArchivedAggregationsFromLocationIdentifierAndDataType<TData = Awaited<ReturnType<typeof getAggregationArchivedAggregationsFromLocationIdentifierAndDataType>>, TError = ProblemDetails>(
 locationIdentifier: string,
    dataType: string,
    params?: GetAggregationArchivedAggregationsFromLocationIdentifierAndDataTypeParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAggregationArchivedAggregationsFromLocationIdentifierAndDataType>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAggregationArchivedAggregationsFromLocationIdentifierAndDataTypeQueryOptions(locationIdentifier,dataType,params,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



