/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * ATSPM Report Api
 * ATSPM Reporting with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';

import type {
  PedDelayResult
} from '../report-api.schemas';


export const getGetPedDelayTestDataResponseMock = (): PedDelayResult[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})))

export const getGetPedDelayReportDataResponseMock = (): PedDelayResult[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})))


export const getGetPedDelayTestDataMockHandler = (overrideResponse?: PedDelayResult[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PedDelayResult[]> | PedDelayResult[])) => {
  return http.get('*/api/v1/PedDelay/test', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetPedDelayTestDataResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetPedDelayReportDataMockHandler = (overrideResponse?: PedDelayResult[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PedDelayResult[]> | PedDelayResult[])) => {
  return http.post('*/api/v1/PedDelay/getReportData', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetPedDelayReportDataResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getPedDelayMock = () => [
  getGetPedDelayTestDataMockHandler(),
  getGetPedDelayReportDataMockHandler()
]
