/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * ATSPM Report Api
 * ATSPM Reporting with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  LeftTurnGapDataCheckResult
} from '../report-api.schemas';

import {
  getGetLeftTurnGapReportDataCheckReportDataResponseMock,
  getGetLeftTurnGapReportDataCheckTestDataResponseMock
} from './left-turn-gap-report-data-check.faker';

export { getGetLeftTurnGapReportDataCheckTestDataResponseMock, getGetLeftTurnGapReportDataCheckReportDataResponseMock } from './left-turn-gap-report-data-check.faker';


export const getGetLeftTurnGapReportDataCheckTestDataMockHandler = (overrideResponse?: LeftTurnGapDataCheckResult | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<LeftTurnGapDataCheckResult> | LeftTurnGapDataCheckResult), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/LeftTurnGapReportDataCheck/test', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetLeftTurnGapReportDataCheckTestDataResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetLeftTurnGapReportDataCheckReportDataMockHandler = (overrideResponse?: LeftTurnGapDataCheckResult | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<LeftTurnGapDataCheckResult> | LeftTurnGapDataCheckResult), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/LeftTurnGapReportDataCheck/getReportData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetLeftTurnGapReportDataCheckReportDataResponseMock(),
      { status: 200
      })
  }, options)
}
export const getLeftTurnGapReportDataCheckMock = () => [
  getGetLeftTurnGapReportDataCheckTestDataMockHandler(),
  getGetLeftTurnGapReportDataCheckReportDataMockHandler()
]
