// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using ATSPM.Data.Enums;
using ATSPM.Data.Interfaces;
using ATSPM.Data.Models.ConfigurationModels;
using ATSPM.Data.Relationships;

namespace ATSPM.Data.Models
{
    /// <summary>
    /// Location that data is being logged and monitored
    /// </summary>
    public partial class Location :
        AtspmConfigModelBase<int>,
        ILocationLayer,
        IRelatedLocationType,
        IRelatedJurisdiction, 
        IRelatedRegion, 
        IRelatedApproaches, 
        IRelatedAreas,
        IRelatedDevices
    {
        /// <summary>
        /// Latitude of location
        /// </summary>
        public double Latitude { get; set; }

        /// <summary>
        /// Longitude of location
        /// </summary>
        public double Longitude { get; set; }

        /// <summary>
        /// Priamry name of location
        /// </summary>
        public string PrimaryName { get; set; }
        
        /// <summary>
        /// Secondary name of location
        /// </summary>
        public string SecondaryName { get; set; }
        
        /// <summary>
        /// Enable location to be charted
        /// </summary>
        public bool ChartEnabled { get; set; }
        
        /// <summary>
        /// Version action of location
        /// </summary>
        public LocationVersionActions VersionAction { get; set; }
        
        /// <summary>
        /// Note
        /// </summary>
        public string Note { get; set; }
        
        /// <summary>
        /// Start date location became active
        /// </summary>
        public DateTime Start { get; set; }

        //TODO: update comment
        /// <summary>
        /// PedsAre1to1
        /// </summary>
        public bool PedsAre1to1 { get; set; }

        #region IlocationLayer

        /// <inheritdoc/>
        public string LocationIdentifier { get; set; }

        #endregion

        #region IRelatedJurisdiction

        /// <inheritdoc/>
        public int? JurisdictionId { get; set; }

        /// <inheritdoc/>
        public virtual Jurisdiction? Jurisdiction { get; set; }

        #endregion

        #region IRelatedLocationType

        /// <inheritdoc/>
        public int LocationTypeId { get; set; }

        /// <inheritdoc/>
        public virtual LocationType LocationType { get; set; }

        #endregion

        #region IRelatedRegion

        /// <inheritdoc/>
        public int? RegionId { get; set; }

        /// <inheritdoc/>
        public virtual Region? Region { get; set; }

        #endregion

        #region IRelatedApproaches

        /// <inheritdoc/>
        public virtual ICollection<Approach> Approaches { get; set; } = new HashSet<Approach>();

        #endregion

        #region IRelatedAreas

        /// <inheritdoc/>
        public virtual ICollection<Area> Areas { get; set; } = new HashSet<Area>();

        #endregion

        #region IRelatedDevices

        /// <inheritdoc/>
        public virtual ICollection<Device> Devices { get; set; } = new HashSet<Device>();

        #endregion

        /// <inheritdoc/>
        public override string ToString() => $"{Id} - {LocationIdentifier} - {PrimaryName} {SecondaryName}";
    }
}