/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * ATSPM Report Api
 * ATSPM Reporting with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';

import type {
  PurdueCoordinationDiagramResult
} from '../report-api.schemas';


export const getGetPurdueCoordinationDiagramTestDataResponseMock = (): PurdueCoordinationDiagramResult[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})))

export const getGetPurdueCoordinationDiagramReportDataResponseMock = (): PurdueCoordinationDiagramResult[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})))


export const getGetPurdueCoordinationDiagramTestDataMockHandler = (overrideResponse?: PurdueCoordinationDiagramResult[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PurdueCoordinationDiagramResult[]> | PurdueCoordinationDiagramResult[])) => {
  return http.get('*/api/v1/PurdueCoordinationDiagram/test', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetPurdueCoordinationDiagramTestDataResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetPurdueCoordinationDiagramReportDataMockHandler = (overrideResponse?: PurdueCoordinationDiagramResult[] | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PurdueCoordinationDiagramResult[]> | PurdueCoordinationDiagramResult[])) => {
  return http.post('*/api/v1/PurdueCoordinationDiagram/getReportData', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetPurdueCoordinationDiagramReportDataResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getPurdueCoordinationDiagramMock = () => [
  getGetPurdueCoordinationDiagramTestDataMockHandler(),
  getGetPurdueCoordinationDiagramReportDataMockHandler()
]
