/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * ATSPM Report Api
 * ATSPM Reporting with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  ProblemDetails,
  TimingAndActuationsForPhaseResult,
  TimingAndActuationsOptions
} from '../report-api.schemas';

import { reportsRequest } from '../../../lib/axios';




export type getTimingAndActuationTestDataResponse200 = {
  data: TimingAndActuationsForPhaseResult[]
  status: 200
}

export type getTimingAndActuationTestDataResponse406 = {
  data: ProblemDetails
  status: 406
}

export type getTimingAndActuationTestDataResponseSuccess = (getTimingAndActuationTestDataResponse200) & {
  headers: Headers;
};
export type getTimingAndActuationTestDataResponseError = (getTimingAndActuationTestDataResponse406) & {
  headers: Headers;
};

export type getTimingAndActuationTestDataResponse = (getTimingAndActuationTestDataResponseSuccess | getTimingAndActuationTestDataResponseError)

export const getGetTimingAndActuationTestDataUrl = () => {




  return `/api/v1/TimingAndActuation/test`
}

/**
 * @summary Get example data for testing
 */
export const getTimingAndActuationTestData = async ( options?: RequestInit): Promise<getTimingAndActuationTestDataResponse> => {

  return reportsRequest<getTimingAndActuationTestDataResponse>(getGetTimingAndActuationTestDataUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTimingAndActuationTestDataQueryKey = () => {
    return [
    `/api/v1/TimingAndActuation/test`
    ] as const;
    }


export const getGetTimingAndActuationTestDataQueryOptions = <TData = Awaited<ReturnType<typeof getTimingAndActuationTestData>>, TError = ProblemDetails>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTimingAndActuationTestData>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTimingAndActuationTestDataQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTimingAndActuationTestData>>> = ({ signal }) => getTimingAndActuationTestData({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTimingAndActuationTestData>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTimingAndActuationTestDataQueryResult = NonNullable<Awaited<ReturnType<typeof getTimingAndActuationTestData>>>
export type GetTimingAndActuationTestDataQueryError = ProblemDetails


/**
 * @summary Get example data for testing
 */

export function useGetTimingAndActuationTestData<TData = Awaited<ReturnType<typeof getTimingAndActuationTestData>>, TError = ProblemDetails>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTimingAndActuationTestData>>, TError, TData>, }

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTimingAndActuationTestDataQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getTimingAndActuationReportDataResponse200 = {
  data: TimingAndActuationsForPhaseResult[]
  status: 200
}

export type getTimingAndActuationReportDataResponse400 = {
  data: ProblemDetails
  status: 400
}

export type getTimingAndActuationReportDataResponse406 = {
  data: ProblemDetails
  status: 406
}

export type getTimingAndActuationReportDataResponseSuccess = (getTimingAndActuationReportDataResponse200) & {
  headers: Headers;
};
export type getTimingAndActuationReportDataResponseError = (getTimingAndActuationReportDataResponse400 | getTimingAndActuationReportDataResponse406) & {
  headers: Headers;
};

export type getTimingAndActuationReportDataResponse = (getTimingAndActuationReportDataResponseSuccess | getTimingAndActuationReportDataResponseError)

export const getGetTimingAndActuationReportDataUrl = () => {




  return `/api/v1/TimingAndActuation/getReportData`
}

/**
 * @summary Get report data
 */
export const getTimingAndActuationReportData = async (timingAndActuationsOptions?: TimingAndActuationsOptions, options?: RequestInit): Promise<getTimingAndActuationReportDataResponse> => {

  return reportsRequest<getTimingAndActuationReportDataResponse>(getGetTimingAndActuationReportDataUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      timingAndActuationsOptions,)
  }
);}




export const getGetTimingAndActuationReportDataMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getTimingAndActuationReportData>>, TError,{data?: TimingAndActuationsOptions}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getTimingAndActuationReportData>>, TError,{data?: TimingAndActuationsOptions}, TContext> => {

const mutationKey = ['getTimingAndActuationReportData'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getTimingAndActuationReportData>>, {data?: TimingAndActuationsOptions}> = (props) => {
          const {data} = props ?? {};

          return  getTimingAndActuationReportData(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetTimingAndActuationReportDataMutationResult = NonNullable<Awaited<ReturnType<typeof getTimingAndActuationReportData>>>
    export type GetTimingAndActuationReportDataMutationBody = TimingAndActuationsOptions | undefined
    export type GetTimingAndActuationReportDataMutationError = ProblemDetails

    /**
 * @summary Get report data
 */
export const useGetTimingAndActuationReportData = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getTimingAndActuationReportData>>, TError,{data?: TimingAndActuationsOptions}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof getTimingAndActuationReportData>>,
        TError,
        {data?: TimingAndActuationsOptions},
        TContext
      > => {
      return useMutation(getGetTimingAndActuationReportDataMutationOptions(options));
    }
