name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main # or your default branch

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate gcloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud Platform
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate Docker to Artifact Registry
        run: |
          gcloud auth configure-docker "us-docker.pkg.dev"

      - name: Build and push Docker image to Google Artifact Registry
        run: |
          gcloud auth configure-docker
          docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/atspm/atspmwebsite:${{ github.sha }} .
          docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/atspm/atspmwebsite:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: atspm-website
          region:
            us-west3
            # NOTE: If using a pre-built image, update the image name here
          image: us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/atspm/atspmwebsite:${{ github.sha }}

    # - name: Deploy to Google Cloud Run
    #   run: |
    #     gcloud run deploy --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/atspmwebsite:$GITHUB_SHA --region us-west3 --platform managed
