/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * ATSPM Report Api
 * ATSPM Reporting with OpenAPI, Swashbuckle, and API versioning.
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  VolumeResult
} from '../report-api.schemas';


export const getGetLeftTurnVolumeTestDataResponseMock = (overrideResponse: Partial<Extract<VolumeResult, object>> = {}): VolumeResult => ({opposingLanes: faker.helpers.arrayElement([faker.number.int(), undefined]), crossProductReview: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), decisionBoundariesReview: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), leftTurnVolume: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), opposingThroughVolume: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), crossProductValue: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), calculatedVolumeBoundary: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), demandList: faker.helpers.arrayElement([faker.helpers.arrayElement([{
        [faker.string.alphanumeric(5)]: faker.number.float({fractionDigits: 2})
      },null,]), undefined]), direction: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), opposingDirection: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), ...overrideResponse})

export const getGetLeftTurnVolumeReportDataResponseMock = (overrideResponse: Partial<Extract<VolumeResult, object>> = {}): VolumeResult => ({opposingLanes: faker.helpers.arrayElement([faker.number.int(), undefined]), crossProductReview: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), decisionBoundariesReview: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), leftTurnVolume: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), opposingThroughVolume: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), crossProductValue: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), calculatedVolumeBoundary: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), demandList: faker.helpers.arrayElement([faker.helpers.arrayElement([{
        [faker.string.alphanumeric(5)]: faker.number.float({fractionDigits: 2})
      },null,]), undefined]), direction: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), opposingDirection: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), ...overrideResponse})


export const getGetLeftTurnVolumeTestDataMockHandler = (overrideResponse?: VolumeResult | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<VolumeResult> | VolumeResult), options?: RequestHandlerOptions) => {
  return http.get('*/api/v1/LeftTurnVolume/test', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetLeftTurnVolumeTestDataResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetLeftTurnVolumeReportDataMockHandler = (overrideResponse?: VolumeResult | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<VolumeResult> | VolumeResult), options?: RequestHandlerOptions) => {
  return http.post('*/api/v1/LeftTurnVolume/getReportData', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetLeftTurnVolumeReportDataResponseMock(),
      { status: 200
      })
  }, options)
}
export const getLeftTurnVolumeMock = () => [
  getGetLeftTurnVolumeTestDataMockHandler(),
  getGetLeftTurnVolumeReportDataMockHandler()
]
