name: Tag Version Bump

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to find branches containing the tag commit

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG_NAME#v}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Detect source branch
        id: detect_branch
        run: |
          BRANCH=$(git branch -r --contains $GITHUB_SHA | grep -v '\->' | head -n 1 | sed 's|origin/||' | xargs)
          if [ -z "$BRANCH" ]; then
            BRANCH="main"
            echo "No branch detected — falling back to 'main'"
          else
            echo "Detected branch: '$BRANCH'"
          fi
          echo "BRANCH=$BRANCH" >> $GITHUB_OUTPUT

      - name: Debug branch
        run: |
          echo "Branch: ${{ steps.detect_branch.outputs.BRANCH }}"

      - name: Checkout source branch
        run: |
          git checkout ${{ steps.detect_branch.outputs.BRANCH }}

      - name: Update .csproj versions
        run: |
          VERSION="${{ steps.extract_version.outputs.VERSION }}"
          find . -name "*.csproj" | while read csproj; do
            echo "Updating $csproj to version $VERSION"
            sed -i 's|<Version>.*</Version>|<Version>'"$VERSION"'</Version>|' "$csproj"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Bump version to ${{ steps.extract_version.outputs.VERSION }}"

          echo "trying to push to: HEAD:${{ steps.detect_branch.outputs.BRANCH }}"
          
          if [ -n "${{ steps.detect_branch.outputs.BRANCH }}" ]; then
            git push origin HEAD:${{ steps.detect_branch.outputs.BRANCH }}
          else
            echo "No branch to push to; skipping push."
          fi
