name: Manual Version Bump

on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'New version number (e.g., 1.2.3)'
        required: true
        type: string

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update .csproj versions
        run: |
          find . -name "*.csproj" | while read csproj; do
            echo "Updating $csproj to version ${{ github.event.inputs.newVersion }}"
            sed -i 's|<Version>.*</Version>|<Version>${{ github.event.inputs.newVersion }}</Version>|' "$csproj"
          done

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Bump version to ${{ github.event.inputs.newVersion }}"
          git push
