name: Update .NET Project Versions

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version number (e.g., 1.2.3)'
        required: true
        type: string

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download dotnet-project-version-updater
      run: |
        curl -L -o updater.zip https://github.com/antonfirsov/dotnet-project-version-updater/releases/latest/download/dotnet-project-version-updater-linux-x64.zip
        unzip updater.zip -d updater
        chmod +x updater/dotnet-project-version-updater

    - name: Run version updater
      run: ./updater/dotnet-project-version-updater --version ${{ github.event.inputs.version }}

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -am "Update project version to ${{ github.event.inputs.version }}"
        git push
